//go:build go1.22

// Package vcrest provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package vcrest

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/nullable"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Disc Details about a disc source.  Included if the source is a disc.
type Disc struct {
	// AllFilesAdded Indicates whether all files from the disc have been added
	AllFilesAdded nullable.Nullable[bool] `json:"allFilesAdded,omitempty"`

	// OrigDirName Original directory name of the disc
	OrigDirName nullable.Nullable[string] `json:"origDirName,omitempty"`

	// Path Filesystem path where the disc is located
	Path nullable.Nullable[string] `json:"path,omitempty"`
}

// Error defines model for Error.
type Error struct {
	// Code Error code
	Code *string `json:"code,omitempty"`

	// Message Error message
	Message string `json:"message"`
}

// File Details about a file source. Included if the source is a file.
type File struct {
	// Path Filesystem path of the file
	Path nullable.Nullable[string] `json:"path,omitempty"`
}

// Movie Details specific to movie works.  Included if the work is a movie.
type Movie struct {
	// ReleaseYear Release year of the movie
	ReleaseYear nullable.Nullable[int] `json:"releaseYear,omitempty"`

	// Title Title of the movie
	Title nullable.Nullable[string] `json:"title,omitempty"`

	// TmdbId The Movie Database (TMDb) identifier for the movie
	TmdbId nullable.Nullable[int] `json:"tmdbId,omitempty"`
}

// MovieEdition Details about a specific edition of a movie.  Included if the work has a movie edition.
type MovieEdition struct {
	// EditionType Type of the movie edition (e.g., "Director's Cut", "Theatrical")
	EditionType nullable.Nullable[string] `json:"editionType,omitempty"`
}

// Source defines model for Source.
type Source struct {
	// Disc Details about a disc source.  Included if the source is a disc.
	Disc *Disc `json:"disc,omitempty"`

	// File Details about a file source. Included if the source is a file.
	File *File `json:"file,omitempty"`

	// Uuid Unique identifier for the source
	Uuid openapi_types.UUID `json:"uuid"`

	// WorkUuids Optional array of work UUIDs associated with this source
	WorkUuids []openapi_types.UUID `json:"workUuids,omitempty"`
}

// Work defines model for Work.
type Work struct {
	// Movie Details specific to movie works.  Included if the work is a movie.
	Movie *Movie `json:"movie,omitempty"`

	// MovieEdition Details about a specific edition of a movie.  Included if the work has a movie edition.
	MovieEdition *MovieEdition `json:"movieEdition,omitempty"`

	// SourceUuids Optional array of source UUIDs associated with this work
	SourceUuids []openapi_types.UUID `json:"sourceUuids,omitempty"`

	// Uuid Unique identifier for the work
	Uuid openapi_types.UUID `json:"uuid"`
}

// PutDiscSourceJSONRequestBody defines body for PutDiscSource for application/json ContentType.
type PutDiscSourceJSONRequestBody = Disc

// PutFileSourceJSONRequestBody defines body for PutFileSource for application/json ContentType.
type PutFileSourceJSONRequestBody = File

// PatchMovieWorkJSONRequestBody defines body for PatchMovieWork for application/json ContentType.
type PatchMovieWorkJSONRequestBody = Movie

// PutMovieWorkJSONRequestBody defines body for PutMovieWork for application/json ContentType.
type PutMovieWorkJSONRequestBody = Movie

// PatchMovieEditionJSONRequestBody defines body for PatchMovieEdition for application/json ContentType.
type PatchMovieEditionJSONRequestBody = MovieEdition

// PutMovieEditionJSONRequestBody defines body for PutMovieEdition for application/json ContentType.
type PutMovieEditionJSONRequestBody = MovieEdition

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetSource request
	GetSource(ctx context.Context, uuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutDiscSourceWithBody request with any body
	PutDiscSourceWithBody(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PutDiscSource(ctx context.Context, uuid openapi_types.UUID, body PutDiscSourceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutFileSourceWithBody request with any body
	PutFileSourceWithBody(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PutFileSource(ctx context.Context, uuid openapi_types.UUID, body PutFileSourceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetWork request
	GetWork(ctx context.Context, uuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PatchMovieWorkWithBody request with any body
	PatchMovieWorkWithBody(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PatchMovieWork(ctx context.Context, uuid openapi_types.UUID, body PatchMovieWorkJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutMovieWorkWithBody request with any body
	PutMovieWorkWithBody(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PutMovieWork(ctx context.Context, uuid openapi_types.UUID, body PutMovieWorkJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PatchMovieEditionWithBody request with any body
	PatchMovieEditionWithBody(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PatchMovieEdition(ctx context.Context, uuid openapi_types.UUID, body PatchMovieEditionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutMovieEditionWithBody request with any body
	PutMovieEditionWithBody(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PutMovieEdition(ctx context.Context, uuid openapi_types.UUID, body PutMovieEditionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetSource(ctx context.Context, uuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSourceRequest(c.Server, uuid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutDiscSourceWithBody(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutDiscSourceRequestWithBody(c.Server, uuid, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutDiscSource(ctx context.Context, uuid openapi_types.UUID, body PutDiscSourceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutDiscSourceRequest(c.Server, uuid, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutFileSourceWithBody(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutFileSourceRequestWithBody(c.Server, uuid, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutFileSource(ctx context.Context, uuid openapi_types.UUID, body PutFileSourceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutFileSourceRequest(c.Server, uuid, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetWork(ctx context.Context, uuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetWorkRequest(c.Server, uuid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchMovieWorkWithBody(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchMovieWorkRequestWithBody(c.Server, uuid, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchMovieWork(ctx context.Context, uuid openapi_types.UUID, body PatchMovieWorkJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchMovieWorkRequest(c.Server, uuid, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutMovieWorkWithBody(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutMovieWorkRequestWithBody(c.Server, uuid, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutMovieWork(ctx context.Context, uuid openapi_types.UUID, body PutMovieWorkJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutMovieWorkRequest(c.Server, uuid, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchMovieEditionWithBody(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchMovieEditionRequestWithBody(c.Server, uuid, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchMovieEdition(ctx context.Context, uuid openapi_types.UUID, body PatchMovieEditionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchMovieEditionRequest(c.Server, uuid, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutMovieEditionWithBody(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutMovieEditionRequestWithBody(c.Server, uuid, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutMovieEdition(ctx context.Context, uuid openapi_types.UUID, body PutMovieEditionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutMovieEditionRequest(c.Server, uuid, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetSourceRequest generates requests for GetSource
func NewGetSourceRequest(server string, uuid openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "uuid", runtime.ParamLocationPath, uuid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sources/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPutDiscSourceRequest calls the generic PutDiscSource builder with application/json body
func NewPutDiscSourceRequest(server string, uuid openapi_types.UUID, body PutDiscSourceJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutDiscSourceRequestWithBody(server, uuid, "application/json", bodyReader)
}

// NewPutDiscSourceRequestWithBody generates requests for PutDiscSource with any type of body
func NewPutDiscSourceRequestWithBody(server string, uuid openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "uuid", runtime.ParamLocationPath, uuid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sources/%s/disc", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPutFileSourceRequest calls the generic PutFileSource builder with application/json body
func NewPutFileSourceRequest(server string, uuid openapi_types.UUID, body PutFileSourceJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutFileSourceRequestWithBody(server, uuid, "application/json", bodyReader)
}

// NewPutFileSourceRequestWithBody generates requests for PutFileSource with any type of body
func NewPutFileSourceRequestWithBody(server string, uuid openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "uuid", runtime.ParamLocationPath, uuid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sources/%s/file", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetWorkRequest generates requests for GetWork
func NewGetWorkRequest(server string, uuid openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "uuid", runtime.ParamLocationPath, uuid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/works/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPatchMovieWorkRequest calls the generic PatchMovieWork builder with application/json body
func NewPatchMovieWorkRequest(server string, uuid openapi_types.UUID, body PatchMovieWorkJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPatchMovieWorkRequestWithBody(server, uuid, "application/json", bodyReader)
}

// NewPatchMovieWorkRequestWithBody generates requests for PatchMovieWork with any type of body
func NewPatchMovieWorkRequestWithBody(server string, uuid openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "uuid", runtime.ParamLocationPath, uuid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/works/%s/movie", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPutMovieWorkRequest calls the generic PutMovieWork builder with application/json body
func NewPutMovieWorkRequest(server string, uuid openapi_types.UUID, body PutMovieWorkJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutMovieWorkRequestWithBody(server, uuid, "application/json", bodyReader)
}

// NewPutMovieWorkRequestWithBody generates requests for PutMovieWork with any type of body
func NewPutMovieWorkRequestWithBody(server string, uuid openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "uuid", runtime.ParamLocationPath, uuid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/works/%s/movie", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPatchMovieEditionRequest calls the generic PatchMovieEdition builder with application/json body
func NewPatchMovieEditionRequest(server string, uuid openapi_types.UUID, body PatchMovieEditionJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPatchMovieEditionRequestWithBody(server, uuid, "application/json", bodyReader)
}

// NewPatchMovieEditionRequestWithBody generates requests for PatchMovieEdition with any type of body
func NewPatchMovieEditionRequestWithBody(server string, uuid openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "uuid", runtime.ParamLocationPath, uuid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/works/%s/movie_edition", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPutMovieEditionRequest calls the generic PutMovieEdition builder with application/json body
func NewPutMovieEditionRequest(server string, uuid openapi_types.UUID, body PutMovieEditionJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutMovieEditionRequestWithBody(server, uuid, "application/json", bodyReader)
}

// NewPutMovieEditionRequestWithBody generates requests for PutMovieEdition with any type of body
func NewPutMovieEditionRequestWithBody(server string, uuid openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "uuid", runtime.ParamLocationPath, uuid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/works/%s/movie_edition", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetSourceWithResponse request
	GetSourceWithResponse(ctx context.Context, uuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetSourceResponse, error)

	// PutDiscSourceWithBodyWithResponse request with any body
	PutDiscSourceWithBodyWithResponse(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutDiscSourceResponse, error)

	PutDiscSourceWithResponse(ctx context.Context, uuid openapi_types.UUID, body PutDiscSourceJSONRequestBody, reqEditors ...RequestEditorFn) (*PutDiscSourceResponse, error)

	// PutFileSourceWithBodyWithResponse request with any body
	PutFileSourceWithBodyWithResponse(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutFileSourceResponse, error)

	PutFileSourceWithResponse(ctx context.Context, uuid openapi_types.UUID, body PutFileSourceJSONRequestBody, reqEditors ...RequestEditorFn) (*PutFileSourceResponse, error)

	// GetWorkWithResponse request
	GetWorkWithResponse(ctx context.Context, uuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetWorkResponse, error)

	// PatchMovieWorkWithBodyWithResponse request with any body
	PatchMovieWorkWithBodyWithResponse(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchMovieWorkResponse, error)

	PatchMovieWorkWithResponse(ctx context.Context, uuid openapi_types.UUID, body PatchMovieWorkJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchMovieWorkResponse, error)

	// PutMovieWorkWithBodyWithResponse request with any body
	PutMovieWorkWithBodyWithResponse(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutMovieWorkResponse, error)

	PutMovieWorkWithResponse(ctx context.Context, uuid openapi_types.UUID, body PutMovieWorkJSONRequestBody, reqEditors ...RequestEditorFn) (*PutMovieWorkResponse, error)

	// PatchMovieEditionWithBodyWithResponse request with any body
	PatchMovieEditionWithBodyWithResponse(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchMovieEditionResponse, error)

	PatchMovieEditionWithResponse(ctx context.Context, uuid openapi_types.UUID, body PatchMovieEditionJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchMovieEditionResponse, error)

	// PutMovieEditionWithBodyWithResponse request with any body
	PutMovieEditionWithBodyWithResponse(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutMovieEditionResponse, error)

	PutMovieEditionWithResponse(ctx context.Context, uuid openapi_types.UUID, body PutMovieEditionJSONRequestBody, reqEditors ...RequestEditorFn) (*PutMovieEditionResponse, error)
}

type GetSourceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Source
	JSON400      *Error
	JSON404      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r GetSourceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSourceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PutDiscSourceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *Error
	JSON409      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r PutDiscSourceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutDiscSourceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PutFileSourceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *Error
	JSON409      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r PutFileSourceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutFileSourceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetWorkResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Work
	JSON400      *Error
	JSON404      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r GetWorkResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetWorkResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PatchMovieWorkResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *Error
	JSON404      *Error
	JSON409      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r PatchMovieWorkResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PatchMovieWorkResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PutMovieWorkResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *Error
	JSON409      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r PutMovieWorkResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutMovieWorkResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PatchMovieEditionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *Error
	JSON404      *Error
	JSON409      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r PatchMovieEditionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PatchMovieEditionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PutMovieEditionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *Error
	JSON409      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r PutMovieEditionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutMovieEditionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetSourceWithResponse request returning *GetSourceResponse
func (c *ClientWithResponses) GetSourceWithResponse(ctx context.Context, uuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetSourceResponse, error) {
	rsp, err := c.GetSource(ctx, uuid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSourceResponse(rsp)
}

// PutDiscSourceWithBodyWithResponse request with arbitrary body returning *PutDiscSourceResponse
func (c *ClientWithResponses) PutDiscSourceWithBodyWithResponse(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutDiscSourceResponse, error) {
	rsp, err := c.PutDiscSourceWithBody(ctx, uuid, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutDiscSourceResponse(rsp)
}

func (c *ClientWithResponses) PutDiscSourceWithResponse(ctx context.Context, uuid openapi_types.UUID, body PutDiscSourceJSONRequestBody, reqEditors ...RequestEditorFn) (*PutDiscSourceResponse, error) {
	rsp, err := c.PutDiscSource(ctx, uuid, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutDiscSourceResponse(rsp)
}

// PutFileSourceWithBodyWithResponse request with arbitrary body returning *PutFileSourceResponse
func (c *ClientWithResponses) PutFileSourceWithBodyWithResponse(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutFileSourceResponse, error) {
	rsp, err := c.PutFileSourceWithBody(ctx, uuid, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutFileSourceResponse(rsp)
}

func (c *ClientWithResponses) PutFileSourceWithResponse(ctx context.Context, uuid openapi_types.UUID, body PutFileSourceJSONRequestBody, reqEditors ...RequestEditorFn) (*PutFileSourceResponse, error) {
	rsp, err := c.PutFileSource(ctx, uuid, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutFileSourceResponse(rsp)
}

// GetWorkWithResponse request returning *GetWorkResponse
func (c *ClientWithResponses) GetWorkWithResponse(ctx context.Context, uuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetWorkResponse, error) {
	rsp, err := c.GetWork(ctx, uuid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetWorkResponse(rsp)
}

// PatchMovieWorkWithBodyWithResponse request with arbitrary body returning *PatchMovieWorkResponse
func (c *ClientWithResponses) PatchMovieWorkWithBodyWithResponse(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchMovieWorkResponse, error) {
	rsp, err := c.PatchMovieWorkWithBody(ctx, uuid, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchMovieWorkResponse(rsp)
}

func (c *ClientWithResponses) PatchMovieWorkWithResponse(ctx context.Context, uuid openapi_types.UUID, body PatchMovieWorkJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchMovieWorkResponse, error) {
	rsp, err := c.PatchMovieWork(ctx, uuid, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchMovieWorkResponse(rsp)
}

// PutMovieWorkWithBodyWithResponse request with arbitrary body returning *PutMovieWorkResponse
func (c *ClientWithResponses) PutMovieWorkWithBodyWithResponse(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutMovieWorkResponse, error) {
	rsp, err := c.PutMovieWorkWithBody(ctx, uuid, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutMovieWorkResponse(rsp)
}

func (c *ClientWithResponses) PutMovieWorkWithResponse(ctx context.Context, uuid openapi_types.UUID, body PutMovieWorkJSONRequestBody, reqEditors ...RequestEditorFn) (*PutMovieWorkResponse, error) {
	rsp, err := c.PutMovieWork(ctx, uuid, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutMovieWorkResponse(rsp)
}

// PatchMovieEditionWithBodyWithResponse request with arbitrary body returning *PatchMovieEditionResponse
func (c *ClientWithResponses) PatchMovieEditionWithBodyWithResponse(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchMovieEditionResponse, error) {
	rsp, err := c.PatchMovieEditionWithBody(ctx, uuid, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchMovieEditionResponse(rsp)
}

func (c *ClientWithResponses) PatchMovieEditionWithResponse(ctx context.Context, uuid openapi_types.UUID, body PatchMovieEditionJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchMovieEditionResponse, error) {
	rsp, err := c.PatchMovieEdition(ctx, uuid, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchMovieEditionResponse(rsp)
}

// PutMovieEditionWithBodyWithResponse request with arbitrary body returning *PutMovieEditionResponse
func (c *ClientWithResponses) PutMovieEditionWithBodyWithResponse(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutMovieEditionResponse, error) {
	rsp, err := c.PutMovieEditionWithBody(ctx, uuid, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutMovieEditionResponse(rsp)
}

func (c *ClientWithResponses) PutMovieEditionWithResponse(ctx context.Context, uuid openapi_types.UUID, body PutMovieEditionJSONRequestBody, reqEditors ...RequestEditorFn) (*PutMovieEditionResponse, error) {
	rsp, err := c.PutMovieEdition(ctx, uuid, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutMovieEditionResponse(rsp)
}

// ParseGetSourceResponse parses an HTTP response from a GetSourceWithResponse call
func ParseGetSourceResponse(rsp *http.Response) (*GetSourceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSourceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Source
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePutDiscSourceResponse parses an HTTP response from a PutDiscSourceWithResponse call
func ParsePutDiscSourceResponse(rsp *http.Response) (*PutDiscSourceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutDiscSourceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePutFileSourceResponse parses an HTTP response from a PutFileSourceWithResponse call
func ParsePutFileSourceResponse(rsp *http.Response) (*PutFileSourceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutFileSourceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetWorkResponse parses an HTTP response from a GetWorkWithResponse call
func ParseGetWorkResponse(rsp *http.Response) (*GetWorkResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetWorkResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Work
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePatchMovieWorkResponse parses an HTTP response from a PatchMovieWorkWithResponse call
func ParsePatchMovieWorkResponse(rsp *http.Response) (*PatchMovieWorkResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PatchMovieWorkResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePutMovieWorkResponse parses an HTTP response from a PutMovieWorkWithResponse call
func ParsePutMovieWorkResponse(rsp *http.Response) (*PutMovieWorkResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutMovieWorkResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePatchMovieEditionResponse parses an HTTP response from a PatchMovieEditionWithResponse call
func ParsePatchMovieEditionResponse(rsp *http.Response) (*PatchMovieEditionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PatchMovieEditionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePutMovieEditionResponse parses an HTTP response from a PutMovieEditionWithResponse call
func ParsePutMovieEditionResponse(rsp *http.Response) (*PutMovieEditionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutMovieEditionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get a source by UUID
	// (GET /sources/{uuid})
	GetSource(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID)
	// Add (or replace) a disc source with the given UUID.
	// (PUT /sources/{uuid}/disc)
	PutDiscSource(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID)
	// Add (or replace) a file source with the given UUID.
	// (PUT /sources/{uuid}/file)
	PutFileSource(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID)
	// Get a work by UUID
	// (GET /works/{uuid})
	GetWork(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID)
	// Update a movie work with the given uuid.
	// (PATCH /works/{uuid}/movie)
	PatchMovieWork(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID)
	// Add a movie work with the given uuid.
	// (PUT /works/{uuid}/movie)
	PutMovieWork(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID)
	// Update a movie edition work with the given uuid.
	// (PATCH /works/{uuid}/movie_edition)
	PatchMovieEdition(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID)
	// Create (or replace) a movie edition work with the given uuid.
	// (PUT /works/{uuid}/movie_edition)
	PutMovieEdition(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetSource operation middleware
func (siw *ServerInterfaceWrapper) GetSource(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", r.PathValue("uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSource(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutDiscSource operation middleware
func (siw *ServerInterfaceWrapper) PutDiscSource(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", r.PathValue("uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutDiscSource(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutFileSource operation middleware
func (siw *ServerInterfaceWrapper) PutFileSource(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", r.PathValue("uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutFileSource(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWork operation middleware
func (siw *ServerInterfaceWrapper) GetWork(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", r.PathValue("uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWork(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchMovieWork operation middleware
func (siw *ServerInterfaceWrapper) PatchMovieWork(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", r.PathValue("uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchMovieWork(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutMovieWork operation middleware
func (siw *ServerInterfaceWrapper) PutMovieWork(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", r.PathValue("uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutMovieWork(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchMovieEdition operation middleware
func (siw *ServerInterfaceWrapper) PatchMovieEdition(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", r.PathValue("uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchMovieEdition(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutMovieEdition operation middleware
func (siw *ServerInterfaceWrapper) PutMovieEdition(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", r.PathValue("uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutMovieEdition(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/sources/{uuid}", wrapper.GetSource)
	m.HandleFunc("PUT "+options.BaseURL+"/sources/{uuid}/disc", wrapper.PutDiscSource)
	m.HandleFunc("PUT "+options.BaseURL+"/sources/{uuid}/file", wrapper.PutFileSource)
	m.HandleFunc("GET "+options.BaseURL+"/works/{uuid}", wrapper.GetWork)
	m.HandleFunc("PATCH "+options.BaseURL+"/works/{uuid}/movie", wrapper.PatchMovieWork)
	m.HandleFunc("PUT "+options.BaseURL+"/works/{uuid}/movie", wrapper.PutMovieWork)
	m.HandleFunc("PATCH "+options.BaseURL+"/works/{uuid}/movie_edition", wrapper.PatchMovieEdition)
	m.HandleFunc("PUT "+options.BaseURL+"/works/{uuid}/movie_edition", wrapper.PutMovieEdition)

	return m
}

type GetSourceRequestObject struct {
	Uuid openapi_types.UUID `json:"uuid"`
}

type GetSourceResponseObject interface {
	VisitGetSourceResponse(w http.ResponseWriter) error
}

type GetSource200JSONResponse Source

func (response GetSource200JSONResponse) VisitGetSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSource400JSONResponse Error

func (response GetSource400JSONResponse) VisitGetSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetSource404JSONResponse Error

func (response GetSource404JSONResponse) VisitGetSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetSource500JSONResponse Error

func (response GetSource500JSONResponse) VisitGetSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PutDiscSourceRequestObject struct {
	Uuid openapi_types.UUID `json:"uuid"`
	Body *PutDiscSourceJSONRequestBody
}

type PutDiscSourceResponseObject interface {
	VisitPutDiscSourceResponse(w http.ResponseWriter) error
}

type PutDiscSource200Response struct {
}

func (response PutDiscSource200Response) VisitPutDiscSourceResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type PutDiscSource201Response struct {
}

func (response PutDiscSource201Response) VisitPutDiscSourceResponse(w http.ResponseWriter) error {
	w.WriteHeader(201)
	return nil
}

type PutDiscSource400JSONResponse Error

func (response PutDiscSource400JSONResponse) VisitPutDiscSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PutDiscSource409JSONResponse Error

func (response PutDiscSource409JSONResponse) VisitPutDiscSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type PutDiscSource500JSONResponse Error

func (response PutDiscSource500JSONResponse) VisitPutDiscSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PutFileSourceRequestObject struct {
	Uuid openapi_types.UUID `json:"uuid"`
	Body *PutFileSourceJSONRequestBody
}

type PutFileSourceResponseObject interface {
	VisitPutFileSourceResponse(w http.ResponseWriter) error
}

type PutFileSource200Response struct {
}

func (response PutFileSource200Response) VisitPutFileSourceResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type PutFileSource201Response struct {
}

func (response PutFileSource201Response) VisitPutFileSourceResponse(w http.ResponseWriter) error {
	w.WriteHeader(201)
	return nil
}

type PutFileSource400JSONResponse Error

func (response PutFileSource400JSONResponse) VisitPutFileSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PutFileSource409JSONResponse Error

func (response PutFileSource409JSONResponse) VisitPutFileSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type PutFileSource500JSONResponse Error

func (response PutFileSource500JSONResponse) VisitPutFileSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkRequestObject struct {
	Uuid openapi_types.UUID `json:"uuid"`
}

type GetWorkResponseObject interface {
	VisitGetWorkResponse(w http.ResponseWriter) error
}

type GetWork200JSONResponse Work

func (response GetWork200JSONResponse) VisitGetWorkResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetWork400JSONResponse Error

func (response GetWork400JSONResponse) VisitGetWorkResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetWork404JSONResponse Error

func (response GetWork404JSONResponse) VisitGetWorkResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetWork500JSONResponse Error

func (response GetWork500JSONResponse) VisitGetWorkResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PatchMovieWorkRequestObject struct {
	Uuid openapi_types.UUID `json:"uuid"`
	Body *PatchMovieWorkJSONRequestBody
}

type PatchMovieWorkResponseObject interface {
	VisitPatchMovieWorkResponse(w http.ResponseWriter) error
}

type PatchMovieWork200Response struct {
}

func (response PatchMovieWork200Response) VisitPatchMovieWorkResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type PatchMovieWork400JSONResponse Error

func (response PatchMovieWork400JSONResponse) VisitPatchMovieWorkResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PatchMovieWork404JSONResponse Error

func (response PatchMovieWork404JSONResponse) VisitPatchMovieWorkResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PatchMovieWork409JSONResponse Error

func (response PatchMovieWork409JSONResponse) VisitPatchMovieWorkResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type PatchMovieWork500JSONResponse Error

func (response PatchMovieWork500JSONResponse) VisitPatchMovieWorkResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PutMovieWorkRequestObject struct {
	Uuid openapi_types.UUID `json:"uuid"`
	Body *PutMovieWorkJSONRequestBody
}

type PutMovieWorkResponseObject interface {
	VisitPutMovieWorkResponse(w http.ResponseWriter) error
}

type PutMovieWork200Response struct {
}

func (response PutMovieWork200Response) VisitPutMovieWorkResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type PutMovieWork201Response struct {
}

func (response PutMovieWork201Response) VisitPutMovieWorkResponse(w http.ResponseWriter) error {
	w.WriteHeader(201)
	return nil
}

type PutMovieWork400JSONResponse Error

func (response PutMovieWork400JSONResponse) VisitPutMovieWorkResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PutMovieWork409JSONResponse Error

func (response PutMovieWork409JSONResponse) VisitPutMovieWorkResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type PutMovieWork500JSONResponse Error

func (response PutMovieWork500JSONResponse) VisitPutMovieWorkResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PatchMovieEditionRequestObject struct {
	Uuid openapi_types.UUID `json:"uuid"`
	Body *PatchMovieEditionJSONRequestBody
}

type PatchMovieEditionResponseObject interface {
	VisitPatchMovieEditionResponse(w http.ResponseWriter) error
}

type PatchMovieEdition200Response struct {
}

func (response PatchMovieEdition200Response) VisitPatchMovieEditionResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type PatchMovieEdition400JSONResponse Error

func (response PatchMovieEdition400JSONResponse) VisitPatchMovieEditionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PatchMovieEdition404JSONResponse Error

func (response PatchMovieEdition404JSONResponse) VisitPatchMovieEditionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PatchMovieEdition409JSONResponse Error

func (response PatchMovieEdition409JSONResponse) VisitPatchMovieEditionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type PatchMovieEdition500JSONResponse Error

func (response PatchMovieEdition500JSONResponse) VisitPatchMovieEditionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PutMovieEditionRequestObject struct {
	Uuid openapi_types.UUID `json:"uuid"`
	Body *PutMovieEditionJSONRequestBody
}

type PutMovieEditionResponseObject interface {
	VisitPutMovieEditionResponse(w http.ResponseWriter) error
}

type PutMovieEdition200Response struct {
}

func (response PutMovieEdition200Response) VisitPutMovieEditionResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type PutMovieEdition201Response struct {
}

func (response PutMovieEdition201Response) VisitPutMovieEditionResponse(w http.ResponseWriter) error {
	w.WriteHeader(201)
	return nil
}

type PutMovieEdition400JSONResponse Error

func (response PutMovieEdition400JSONResponse) VisitPutMovieEditionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PutMovieEdition409JSONResponse Error

func (response PutMovieEdition409JSONResponse) VisitPutMovieEditionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type PutMovieEdition500JSONResponse Error

func (response PutMovieEdition500JSONResponse) VisitPutMovieEditionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get a source by UUID
	// (GET /sources/{uuid})
	GetSource(ctx context.Context, request GetSourceRequestObject) (GetSourceResponseObject, error)
	// Add (or replace) a disc source with the given UUID.
	// (PUT /sources/{uuid}/disc)
	PutDiscSource(ctx context.Context, request PutDiscSourceRequestObject) (PutDiscSourceResponseObject, error)
	// Add (or replace) a file source with the given UUID.
	// (PUT /sources/{uuid}/file)
	PutFileSource(ctx context.Context, request PutFileSourceRequestObject) (PutFileSourceResponseObject, error)
	// Get a work by UUID
	// (GET /works/{uuid})
	GetWork(ctx context.Context, request GetWorkRequestObject) (GetWorkResponseObject, error)
	// Update a movie work with the given uuid.
	// (PATCH /works/{uuid}/movie)
	PatchMovieWork(ctx context.Context, request PatchMovieWorkRequestObject) (PatchMovieWorkResponseObject, error)
	// Add a movie work with the given uuid.
	// (PUT /works/{uuid}/movie)
	PutMovieWork(ctx context.Context, request PutMovieWorkRequestObject) (PutMovieWorkResponseObject, error)
	// Update a movie edition work with the given uuid.
	// (PATCH /works/{uuid}/movie_edition)
	PatchMovieEdition(ctx context.Context, request PatchMovieEditionRequestObject) (PatchMovieEditionResponseObject, error)
	// Create (or replace) a movie edition work with the given uuid.
	// (PUT /works/{uuid}/movie_edition)
	PutMovieEdition(ctx context.Context, request PutMovieEditionRequestObject) (PutMovieEditionResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetSource operation middleware
func (sh *strictHandler) GetSource(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	var request GetSourceRequestObject

	request.Uuid = uuid

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSource(ctx, request.(GetSourceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSource")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSourceResponseObject); ok {
		if err := validResponse.VisitGetSourceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutDiscSource operation middleware
func (sh *strictHandler) PutDiscSource(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	var request PutDiscSourceRequestObject

	request.Uuid = uuid

	var body PutDiscSourceJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutDiscSource(ctx, request.(PutDiscSourceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutDiscSource")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutDiscSourceResponseObject); ok {
		if err := validResponse.VisitPutDiscSourceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutFileSource operation middleware
func (sh *strictHandler) PutFileSource(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	var request PutFileSourceRequestObject

	request.Uuid = uuid

	var body PutFileSourceJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutFileSource(ctx, request.(PutFileSourceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutFileSource")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutFileSourceResponseObject); ok {
		if err := validResponse.VisitPutFileSourceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetWork operation middleware
func (sh *strictHandler) GetWork(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	var request GetWorkRequestObject

	request.Uuid = uuid

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetWork(ctx, request.(GetWorkRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetWork")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetWorkResponseObject); ok {
		if err := validResponse.VisitGetWorkResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PatchMovieWork operation middleware
func (sh *strictHandler) PatchMovieWork(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	var request PatchMovieWorkRequestObject

	request.Uuid = uuid

	var body PatchMovieWorkJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PatchMovieWork(ctx, request.(PatchMovieWorkRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchMovieWork")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PatchMovieWorkResponseObject); ok {
		if err := validResponse.VisitPatchMovieWorkResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutMovieWork operation middleware
func (sh *strictHandler) PutMovieWork(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	var request PutMovieWorkRequestObject

	request.Uuid = uuid

	var body PutMovieWorkJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutMovieWork(ctx, request.(PutMovieWorkRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutMovieWork")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutMovieWorkResponseObject); ok {
		if err := validResponse.VisitPutMovieWorkResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PatchMovieEdition operation middleware
func (sh *strictHandler) PatchMovieEdition(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	var request PatchMovieEditionRequestObject

	request.Uuid = uuid

	var body PatchMovieEditionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PatchMovieEdition(ctx, request.(PatchMovieEditionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchMovieEdition")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PatchMovieEditionResponseObject); ok {
		if err := validResponse.VisitPatchMovieEditionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutMovieEdition operation middleware
func (sh *strictHandler) PutMovieEdition(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	var request PutMovieEditionRequestObject

	request.Uuid = uuid

	var body PutMovieEditionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutMovieEdition(ctx, request.(PutMovieEditionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutMovieEdition")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutMovieEditionResponseObject); ok {
		if err := validResponse.VisitPutMovieEditionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xab2/TvBb/KpbvlS5IXf+tG9B3uxSu+mKA2HrRI0DIjU8bg2MH2+moUL/7I9tJmjRp",
	"m26wpxN7RUmOff7+zu/Y2U8cyCiWAoTRePgT6yCEiLifI6YD+y8FHSgWGyYFHuIRGMK4RmQqE4MIokwH",
	"SMtEBdBGaCwCnlCgiM2QCSF9gZhOJdu4hWMlY1CGgdNCOH/NOOgLSoFW1Y0FZQExoNFNCCYEhQjnaGZX",
	"oJmSkdPibAjJAtAUQCDitmph+EGimAMeGpVAC4uEczJd/98sY8BDPJWSAxF41cJSsfmIqTckgqolbxWb",
	"M0E4okxBYKRaIkEiQHKW21DUiS+XNoCjTBhvNUAbxcTc6o+JCauKXXiW2kCErIANhIK130wjLm2ISi7j",
	"jiC6EwFlpHOwJav8iZx+hcBY214pJZU1rpy+QNKaWDlh5N4VbXrz9vrL67eTNyNc43wEWpP51s2y18X9",
	"3kNaX0IaNJOJoLjOFwXfE6ZsdX3MtXyucdEGen/B29rLC35XvVvBar03y3FaVHaLhlntRHLBoB19W9wu",
	"v5d2+XbvdQwBm7EAGYmcJnQj1TddA3n73AfAW1SJgAIORMNfQFRV33v/Ei2BqCwKbp9iGPrdXnerk0wY",
	"mIOyPhlm6jJ6bR9v3RyPRQBetAFkTUSn45q+dR0CciFFI2LI1Lr05PpyNH2KGAVh2IyBQjOptjj4rN89",
	"2+/h1jy+oszbsa+Y87SCX2GjkiVuS2pDkuc2W1XNcfri2llXic0yLoc/1/4E2vN2C33CWVn/R6OXifmE",
	"7bPrEIhRLCD8E35aylhZ+nb1f+WQW21wNGXBfyuY4SH+V2fNl52ULDuOKVctPEsbyC5Z12RWLZwkrKZs",
	"JoJ9T6CuRnxnKbnd75/C4Oz82Qk8fzE96fXp6QkZnJ2fDPrn571B79mg2+3hFp5JFRGDh15lTQ3btE4S",
	"RnUN6bkfhCOiFFnapLkamEzGI42I1jJglnnQDTMhMiHTNXZ+xL39hnZxCw/2i53axs0MRM7WvZ6lD5zx",
	"FSpwi+p44INU36qFEGUNcld2fRe1bLYBw72LMtlVC/sQNs5Iyjk7cmJzVs5Iw9I53S/Wv0tGDofBpitN",
	"a2uPYc1Kw4oxMZNVgy/ejZ2JERFkzsQcLRgF6TkSEUHTJGmckxL+v5N4SQzhco6uQC2Yw80ClPab9trd",
	"dtfNpTEIEjM8xKftbvsU+0nRBbyTbtz5aW1e2UdzMHW8ahIlbOf2jQ55n/K4ztkChKsh7PQpYhdaZsP/",
	"A3OVgTomikRgQGk8/FjJ2mQ8yvp6WpRGIgVGMVjY1cxKuQGohYUbsrN0rIPvG7aHRoOKWn22i3UshfYw",
	"7Xe7fi4VBoQLBIljbs8QTIrOV+3huN5/FzBTt13ey65eJUEAWs8SjjLtNlGDX6jcD9w1usdiQTijLlko",
	"DY/TPfj9uq825+1VC5/dj9MGlG17GtQCFIJUsIV1EkVELX2h2pHGmzhd+mq2Ihsg6WScHic1SLmgVKMn",
	"UiEFMScB6KflU+66K1GrZA943iXGTgeHA6io0Uh7pv2dAPqegDb/lXT5yzLpZ6JyY7WmrerxujGmFpxP",
	"YuroTOeQ4445+t3e7oXuGqCy7F4hmgbW631xb/BcM7+rKMIVELpE8INp4+mIaYfh7FLmmFB8QWkRfpvo",
	"S30rgq5dC/JsGG8O8sLJ/mCQ27H+cJAXNT5EkPvDzC1B/rrg/EEgLy58BHkDkPubqCMHeREL20HuJurm",
	"w649yh026n7wB4zGEHbn4Yc95jqXH4fcXLcrmmMecV3NlQbcIiw6+U1FTExQc9k8cc12fYvnb2wPIjy7",
	"sbu2uC1cfMN/WGyXXu7cku4u17Hexnb/HG3dF6o2SKsEsnshzzorcp5MP1gcE+A9VstQ3WBHCwJn9PZJ",
	"9w5IT8ydcP7gRtrfDvLakdav+wOH2To87hpljxCidpZtgM96mv4C628EDek6+1h2F9rOvjb8Scydf2G5",
	"E7az6D9y+BFz+PrD9BFzeQnHB3H6SwV2o40D9MaudRtuY/c7tIObkAVhzaf8G8Y5mkL+x1iP3eLAYSBb",
	"+jgUNBsKjhPzjaC6Y2iwm7nd6/A4ggVwGUcgTGoDbuFEcTzEoTHxsNPhMiA8lNoMn3efd/Hq8+rvAAAA",
	"//8LwXwd8SkAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
