//go:build go1.22

// Package vcrest provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package vcrest

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Disc Details about a disc source.  Included if the source is a disc.
type Disc struct {
	// AllFilesAdded Indicates whether all files from the disc have been added
	AllFilesAdded bool `json:"allFilesAdded"`

	// OrigDirName Original directory name of the disc
	OrigDirName string `json:"origDirName"`

	// Path Filesystem path where the disc is located
	Path string `json:"path"`
}

// Error defines model for Error.
type Error struct {
	// Code Error code
	Code *string `json:"code,omitempty"`

	// Message Error message
	Message string `json:"message"`
}

// File Details about a file source. Included if the source is a file.
type File struct {
	// Path Filesystem path of the file
	Path string `json:"path"`
}

// Movie Details specific to movie works.  Included if the work is a movie.
type Movie struct {
	// ReleaseYear Release year of the movie
	ReleaseYear *int `json:"releaseYear,omitempty"`

	// Title Title of the movie
	Title string `json:"title"`

	// TmdbId The Movie Database (TMDb) identifier for the movie
	TmdbId *int `json:"tmdbId,omitempty"`
}

// MovieEdition Details about a specific edition of a movie.  Included if the work has a movie edition.
type MovieEdition struct {
	// EditionType Type of the movie edition (e.g., "Director's Cut", "Theatrical")
	EditionType string `json:"editionType"`
}

// Source defines model for Source.
type Source struct {
	// Disc Details about a disc source.  Included if the source is a disc.
	Disc *Disc `json:"disc,omitempty"`

	// File Details about a file source. Included if the source is a file.
	File *File `json:"file,omitempty"`

	// Uuid Unique identifier for the source
	Uuid openapi_types.UUID `json:"uuid"`

	// WorkUuids Optional array of work UUIDs associated with this source
	WorkUuids []openapi_types.UUID `json:"workUuids,omitempty"`
}

// Work defines model for Work.
type Work struct {
	// Movie Details specific to movie works.  Included if the work is a movie.
	Movie *Movie `json:"movie,omitempty"`

	// MovieEdition Details about a specific edition of a movie.  Included if the work has a movie edition.
	MovieEdition *MovieEdition `json:"movieEdition,omitempty"`

	// SourceUuids Optional array of source UUIDs associated with this work
	SourceUuids []openapi_types.UUID `json:"sourceUuids,omitempty"`

	// Uuid Unique identifier for the work
	Uuid openapi_types.UUID `json:"uuid"`
}

// PutDiscSourceJSONBody defines parameters for PutDiscSource.
type PutDiscSourceJSONBody struct {
	// OrigDirName Original directory name of the disc
	OrigDirName string `json:"origDirName"`

	// Path Filesystem path where the disc is located
	Path string `json:"path"`
}

// PutFileSourceJSONBody defines parameters for PutFileSource.
type PutFileSourceJSONBody struct {
	// Path Filesystem path of the file
	Path string `json:"path"`
}

// PutMovieWorkJSONBody defines parameters for PutMovieWork.
type PutMovieWorkJSONBody struct {
	// ReleaseYear Release year of the movie
	ReleaseYear *int `json:"releaseYear,omitempty"`

	// Title Title of the movie
	Title string `json:"title"`

	// TmdbId The Movie Database (TMDb) identifier for the movie
	TmdbId *int `json:"tmdbId,omitempty"`
}

// PutMovieEditionJSONBody defines parameters for PutMovieEdition.
type PutMovieEditionJSONBody struct {
	// EditionType Type of the movie edition (e.g., "Director's Cut", "Theatrical")
	EditionType string `json:"editionType"`
}

// PutDiscSourceJSONRequestBody defines body for PutDiscSource for application/json ContentType.
type PutDiscSourceJSONRequestBody PutDiscSourceJSONBody

// PutFileSourceJSONRequestBody defines body for PutFileSource for application/json ContentType.
type PutFileSourceJSONRequestBody PutFileSourceJSONBody

// PutMovieWorkJSONRequestBody defines body for PutMovieWork for application/json ContentType.
type PutMovieWorkJSONRequestBody PutMovieWorkJSONBody

// PutMovieEditionJSONRequestBody defines body for PutMovieEdition for application/json ContentType.
type PutMovieEditionJSONRequestBody PutMovieEditionJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// AddFileToDisc request
	AddFileToDisc(ctx context.Context, discUuid openapi_types.UUID, fileUuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetSource request
	GetSource(ctx context.Context, uuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutDiscSourceWithBody request with any body
	PutDiscSourceWithBody(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PutDiscSource(ctx context.Context, uuid openapi_types.UUID, body PutDiscSourceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// MarkDiscAllFilesAdded request
	MarkDiscAllFilesAdded(ctx context.Context, uuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutFileSourceWithBody request with any body
	PutFileSourceWithBody(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PutFileSource(ctx context.Context, uuid openapi_types.UUID, body PutFileSourceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AddEditionToMovie request
	AddEditionToMovie(ctx context.Context, movieUuid openapi_types.UUID, editionUuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetWork request
	GetWork(ctx context.Context, uuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutMovieWorkWithBody request with any body
	PutMovieWorkWithBody(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PutMovieWork(ctx context.Context, uuid openapi_types.UUID, body PutMovieWorkJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutMovieEditionWithBody request with any body
	PutMovieEditionWithBody(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PutMovieEdition(ctx context.Context, uuid openapi_types.UUID, body PutMovieEditionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) AddFileToDisc(ctx context.Context, discUuid openapi_types.UUID, fileUuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddFileToDiscRequest(c.Server, discUuid, fileUuid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetSource(ctx context.Context, uuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSourceRequest(c.Server, uuid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutDiscSourceWithBody(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutDiscSourceRequestWithBody(c.Server, uuid, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutDiscSource(ctx context.Context, uuid openapi_types.UUID, body PutDiscSourceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutDiscSourceRequest(c.Server, uuid, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) MarkDiscAllFilesAdded(ctx context.Context, uuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewMarkDiscAllFilesAddedRequest(c.Server, uuid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutFileSourceWithBody(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutFileSourceRequestWithBody(c.Server, uuid, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutFileSource(ctx context.Context, uuid openapi_types.UUID, body PutFileSourceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutFileSourceRequest(c.Server, uuid, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AddEditionToMovie(ctx context.Context, movieUuid openapi_types.UUID, editionUuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddEditionToMovieRequest(c.Server, movieUuid, editionUuid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetWork(ctx context.Context, uuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetWorkRequest(c.Server, uuid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutMovieWorkWithBody(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutMovieWorkRequestWithBody(c.Server, uuid, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutMovieWork(ctx context.Context, uuid openapi_types.UUID, body PutMovieWorkJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutMovieWorkRequest(c.Server, uuid, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutMovieEditionWithBody(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutMovieEditionRequestWithBody(c.Server, uuid, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutMovieEdition(ctx context.Context, uuid openapi_types.UUID, body PutMovieEditionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutMovieEditionRequest(c.Server, uuid, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewAddFileToDiscRequest generates requests for AddFileToDisc
func NewAddFileToDiscRequest(server string, discUuid openapi_types.UUID, fileUuid openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "discUuid", runtime.ParamLocationPath, discUuid)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "fileUuid", runtime.ParamLocationPath, fileUuid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sources/%s/disc/file/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetSourceRequest generates requests for GetSource
func NewGetSourceRequest(server string, uuid openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "uuid", runtime.ParamLocationPath, uuid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sources/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPutDiscSourceRequest calls the generic PutDiscSource builder with application/json body
func NewPutDiscSourceRequest(server string, uuid openapi_types.UUID, body PutDiscSourceJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutDiscSourceRequestWithBody(server, uuid, "application/json", bodyReader)
}

// NewPutDiscSourceRequestWithBody generates requests for PutDiscSource with any type of body
func NewPutDiscSourceRequestWithBody(server string, uuid openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "uuid", runtime.ParamLocationPath, uuid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sources/%s/disc", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewMarkDiscAllFilesAddedRequest generates requests for MarkDiscAllFilesAdded
func NewMarkDiscAllFilesAddedRequest(server string, uuid openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "uuid", runtime.ParamLocationPath, uuid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sources/%s/disc/all_files_added", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPutFileSourceRequest calls the generic PutFileSource builder with application/json body
func NewPutFileSourceRequest(server string, uuid openapi_types.UUID, body PutFileSourceJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutFileSourceRequestWithBody(server, uuid, "application/json", bodyReader)
}

// NewPutFileSourceRequestWithBody generates requests for PutFileSource with any type of body
func NewPutFileSourceRequestWithBody(server string, uuid openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "uuid", runtime.ParamLocationPath, uuid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sources/%s/file", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewAddEditionToMovieRequest generates requests for AddEditionToMovie
func NewAddEditionToMovieRequest(server string, movieUuid openapi_types.UUID, editionUuid openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "movieUuid", runtime.ParamLocationPath, movieUuid)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "editionUuid", runtime.ParamLocationPath, editionUuid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/works/%s/movie/editions/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetWorkRequest generates requests for GetWork
func NewGetWorkRequest(server string, uuid openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "uuid", runtime.ParamLocationPath, uuid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/works/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPutMovieWorkRequest calls the generic PutMovieWork builder with application/json body
func NewPutMovieWorkRequest(server string, uuid openapi_types.UUID, body PutMovieWorkJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutMovieWorkRequestWithBody(server, uuid, "application/json", bodyReader)
}

// NewPutMovieWorkRequestWithBody generates requests for PutMovieWork with any type of body
func NewPutMovieWorkRequestWithBody(server string, uuid openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "uuid", runtime.ParamLocationPath, uuid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/works/%s/movie", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPutMovieEditionRequest calls the generic PutMovieEdition builder with application/json body
func NewPutMovieEditionRequest(server string, uuid openapi_types.UUID, body PutMovieEditionJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutMovieEditionRequestWithBody(server, uuid, "application/json", bodyReader)
}

// NewPutMovieEditionRequestWithBody generates requests for PutMovieEdition with any type of body
func NewPutMovieEditionRequestWithBody(server string, uuid openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "uuid", runtime.ParamLocationPath, uuid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/works/%s/movie_edition", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// AddFileToDiscWithResponse request
	AddFileToDiscWithResponse(ctx context.Context, discUuid openapi_types.UUID, fileUuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*AddFileToDiscResponse, error)

	// GetSourceWithResponse request
	GetSourceWithResponse(ctx context.Context, uuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetSourceResponse, error)

	// PutDiscSourceWithBodyWithResponse request with any body
	PutDiscSourceWithBodyWithResponse(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutDiscSourceResponse, error)

	PutDiscSourceWithResponse(ctx context.Context, uuid openapi_types.UUID, body PutDiscSourceJSONRequestBody, reqEditors ...RequestEditorFn) (*PutDiscSourceResponse, error)

	// MarkDiscAllFilesAddedWithResponse request
	MarkDiscAllFilesAddedWithResponse(ctx context.Context, uuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*MarkDiscAllFilesAddedResponse, error)

	// PutFileSourceWithBodyWithResponse request with any body
	PutFileSourceWithBodyWithResponse(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutFileSourceResponse, error)

	PutFileSourceWithResponse(ctx context.Context, uuid openapi_types.UUID, body PutFileSourceJSONRequestBody, reqEditors ...RequestEditorFn) (*PutFileSourceResponse, error)

	// AddEditionToMovieWithResponse request
	AddEditionToMovieWithResponse(ctx context.Context, movieUuid openapi_types.UUID, editionUuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*AddEditionToMovieResponse, error)

	// GetWorkWithResponse request
	GetWorkWithResponse(ctx context.Context, uuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetWorkResponse, error)

	// PutMovieWorkWithBodyWithResponse request with any body
	PutMovieWorkWithBodyWithResponse(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutMovieWorkResponse, error)

	PutMovieWorkWithResponse(ctx context.Context, uuid openapi_types.UUID, body PutMovieWorkJSONRequestBody, reqEditors ...RequestEditorFn) (*PutMovieWorkResponse, error)

	// PutMovieEditionWithBodyWithResponse request with any body
	PutMovieEditionWithBodyWithResponse(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutMovieEditionResponse, error)

	PutMovieEditionWithResponse(ctx context.Context, uuid openapi_types.UUID, body PutMovieEditionJSONRequestBody, reqEditors ...RequestEditorFn) (*PutMovieEditionResponse, error)
}

type AddFileToDiscResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *Source
	JSON400      *Error
	JSON404      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r AddFileToDiscResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AddFileToDiscResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetSourceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Source
	JSON400      *Error
	JSON404      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r GetSourceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSourceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PutDiscSourceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *Error
	JSON409      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r PutDiscSourceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutDiscSourceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type MarkDiscAllFilesAddedResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Source
	JSON404      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r MarkDiscAllFilesAddedResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r MarkDiscAllFilesAddedResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PutFileSourceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *Error
	JSON409      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r PutFileSourceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutFileSourceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type AddEditionToMovieResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *Error
	JSON404      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r AddEditionToMovieResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AddEditionToMovieResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetWorkResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Work
	JSON400      *Error
	JSON404      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r GetWorkResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetWorkResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PutMovieWorkResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *Error
	JSON409      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r PutMovieWorkResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutMovieWorkResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PutMovieEditionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *Error
	JSON409      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r PutMovieEditionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutMovieEditionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// AddFileToDiscWithResponse request returning *AddFileToDiscResponse
func (c *ClientWithResponses) AddFileToDiscWithResponse(ctx context.Context, discUuid openapi_types.UUID, fileUuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*AddFileToDiscResponse, error) {
	rsp, err := c.AddFileToDisc(ctx, discUuid, fileUuid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAddFileToDiscResponse(rsp)
}

// GetSourceWithResponse request returning *GetSourceResponse
func (c *ClientWithResponses) GetSourceWithResponse(ctx context.Context, uuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetSourceResponse, error) {
	rsp, err := c.GetSource(ctx, uuid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSourceResponse(rsp)
}

// PutDiscSourceWithBodyWithResponse request with arbitrary body returning *PutDiscSourceResponse
func (c *ClientWithResponses) PutDiscSourceWithBodyWithResponse(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutDiscSourceResponse, error) {
	rsp, err := c.PutDiscSourceWithBody(ctx, uuid, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutDiscSourceResponse(rsp)
}

func (c *ClientWithResponses) PutDiscSourceWithResponse(ctx context.Context, uuid openapi_types.UUID, body PutDiscSourceJSONRequestBody, reqEditors ...RequestEditorFn) (*PutDiscSourceResponse, error) {
	rsp, err := c.PutDiscSource(ctx, uuid, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutDiscSourceResponse(rsp)
}

// MarkDiscAllFilesAddedWithResponse request returning *MarkDiscAllFilesAddedResponse
func (c *ClientWithResponses) MarkDiscAllFilesAddedWithResponse(ctx context.Context, uuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*MarkDiscAllFilesAddedResponse, error) {
	rsp, err := c.MarkDiscAllFilesAdded(ctx, uuid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseMarkDiscAllFilesAddedResponse(rsp)
}

// PutFileSourceWithBodyWithResponse request with arbitrary body returning *PutFileSourceResponse
func (c *ClientWithResponses) PutFileSourceWithBodyWithResponse(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutFileSourceResponse, error) {
	rsp, err := c.PutFileSourceWithBody(ctx, uuid, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutFileSourceResponse(rsp)
}

func (c *ClientWithResponses) PutFileSourceWithResponse(ctx context.Context, uuid openapi_types.UUID, body PutFileSourceJSONRequestBody, reqEditors ...RequestEditorFn) (*PutFileSourceResponse, error) {
	rsp, err := c.PutFileSource(ctx, uuid, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutFileSourceResponse(rsp)
}

// AddEditionToMovieWithResponse request returning *AddEditionToMovieResponse
func (c *ClientWithResponses) AddEditionToMovieWithResponse(ctx context.Context, movieUuid openapi_types.UUID, editionUuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*AddEditionToMovieResponse, error) {
	rsp, err := c.AddEditionToMovie(ctx, movieUuid, editionUuid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAddEditionToMovieResponse(rsp)
}

// GetWorkWithResponse request returning *GetWorkResponse
func (c *ClientWithResponses) GetWorkWithResponse(ctx context.Context, uuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetWorkResponse, error) {
	rsp, err := c.GetWork(ctx, uuid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetWorkResponse(rsp)
}

// PutMovieWorkWithBodyWithResponse request with arbitrary body returning *PutMovieWorkResponse
func (c *ClientWithResponses) PutMovieWorkWithBodyWithResponse(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutMovieWorkResponse, error) {
	rsp, err := c.PutMovieWorkWithBody(ctx, uuid, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutMovieWorkResponse(rsp)
}

func (c *ClientWithResponses) PutMovieWorkWithResponse(ctx context.Context, uuid openapi_types.UUID, body PutMovieWorkJSONRequestBody, reqEditors ...RequestEditorFn) (*PutMovieWorkResponse, error) {
	rsp, err := c.PutMovieWork(ctx, uuid, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutMovieWorkResponse(rsp)
}

// PutMovieEditionWithBodyWithResponse request with arbitrary body returning *PutMovieEditionResponse
func (c *ClientWithResponses) PutMovieEditionWithBodyWithResponse(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutMovieEditionResponse, error) {
	rsp, err := c.PutMovieEditionWithBody(ctx, uuid, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutMovieEditionResponse(rsp)
}

func (c *ClientWithResponses) PutMovieEditionWithResponse(ctx context.Context, uuid openapi_types.UUID, body PutMovieEditionJSONRequestBody, reqEditors ...RequestEditorFn) (*PutMovieEditionResponse, error) {
	rsp, err := c.PutMovieEdition(ctx, uuid, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutMovieEditionResponse(rsp)
}

// ParseAddFileToDiscResponse parses an HTTP response from a AddFileToDiscWithResponse call
func ParseAddFileToDiscResponse(rsp *http.Response) (*AddFileToDiscResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AddFileToDiscResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Source
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetSourceResponse parses an HTTP response from a GetSourceWithResponse call
func ParseGetSourceResponse(rsp *http.Response) (*GetSourceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSourceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Source
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePutDiscSourceResponse parses an HTTP response from a PutDiscSourceWithResponse call
func ParsePutDiscSourceResponse(rsp *http.Response) (*PutDiscSourceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutDiscSourceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseMarkDiscAllFilesAddedResponse parses an HTTP response from a MarkDiscAllFilesAddedWithResponse call
func ParseMarkDiscAllFilesAddedResponse(rsp *http.Response) (*MarkDiscAllFilesAddedResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &MarkDiscAllFilesAddedResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Source
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePutFileSourceResponse parses an HTTP response from a PutFileSourceWithResponse call
func ParsePutFileSourceResponse(rsp *http.Response) (*PutFileSourceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutFileSourceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseAddEditionToMovieResponse parses an HTTP response from a AddEditionToMovieWithResponse call
func ParseAddEditionToMovieResponse(rsp *http.Response) (*AddEditionToMovieResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AddEditionToMovieResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetWorkResponse parses an HTTP response from a GetWorkWithResponse call
func ParseGetWorkResponse(rsp *http.Response) (*GetWorkResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetWorkResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Work
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePutMovieWorkResponse parses an HTTP response from a PutMovieWorkWithResponse call
func ParsePutMovieWorkResponse(rsp *http.Response) (*PutMovieWorkResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutMovieWorkResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePutMovieEditionResponse parses an HTTP response from a PutMovieEditionWithResponse call
func ParsePutMovieEditionResponse(rsp *http.Response) (*PutMovieEditionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutMovieEditionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Associates a file source with a disc source
	// (PUT /sources/{discUuid}/disc/file/{fileUuid})
	AddFileToDisc(w http.ResponseWriter, r *http.Request, discUuid openapi_types.UUID, fileUuid openapi_types.UUID)
	// Get a source by UUID
	// (GET /sources/{uuid})
	GetSource(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID)
	// Add a disc source with the given UUID.
	// (PUT /sources/{uuid}/disc)
	PutDiscSource(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID)
	// Mark all files from the disc source as added
	// (PUT /sources/{uuid}/disc/all_files_added)
	MarkDiscAllFilesAdded(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID)
	// Add a file source with the given UUID.
	// (PUT /sources/{uuid}/file)
	PutFileSource(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID)
	// Associate an existing movie edition with a movie work.
	// (PUT /works/{movieUuid}/movie/editions/{editionUuid})
	AddEditionToMovie(w http.ResponseWriter, r *http.Request, movieUuid openapi_types.UUID, editionUuid openapi_types.UUID)
	// Get a work by UUID
	// (GET /works/{uuid})
	GetWork(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID)
	// Add a movie work with the given uuid.
	// (PUT /works/{uuid}/movie)
	PutMovieWork(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID)
	// Create a new movie edition work with the given uuid.
	// (PUT /works/{uuid}/movie_edition)
	PutMovieEdition(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// AddFileToDisc operation middleware
func (siw *ServerInterfaceWrapper) AddFileToDisc(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "discUuid" -------------
	var discUuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "discUuid", r.PathValue("discUuid"), &discUuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "discUuid", Err: err})
		return
	}

	// ------------- Path parameter "fileUuid" -------------
	var fileUuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "fileUuid", r.PathValue("fileUuid"), &fileUuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "fileUuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddFileToDisc(w, r, discUuid, fileUuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSource operation middleware
func (siw *ServerInterfaceWrapper) GetSource(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", r.PathValue("uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSource(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutDiscSource operation middleware
func (siw *ServerInterfaceWrapper) PutDiscSource(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", r.PathValue("uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutDiscSource(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MarkDiscAllFilesAdded operation middleware
func (siw *ServerInterfaceWrapper) MarkDiscAllFilesAdded(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", r.PathValue("uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MarkDiscAllFilesAdded(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutFileSource operation middleware
func (siw *ServerInterfaceWrapper) PutFileSource(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", r.PathValue("uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutFileSource(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddEditionToMovie operation middleware
func (siw *ServerInterfaceWrapper) AddEditionToMovie(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "movieUuid" -------------
	var movieUuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "movieUuid", r.PathValue("movieUuid"), &movieUuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "movieUuid", Err: err})
		return
	}

	// ------------- Path parameter "editionUuid" -------------
	var editionUuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "editionUuid", r.PathValue("editionUuid"), &editionUuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "editionUuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddEditionToMovie(w, r, movieUuid, editionUuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWork operation middleware
func (siw *ServerInterfaceWrapper) GetWork(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", r.PathValue("uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWork(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutMovieWork operation middleware
func (siw *ServerInterfaceWrapper) PutMovieWork(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", r.PathValue("uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutMovieWork(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutMovieEdition operation middleware
func (siw *ServerInterfaceWrapper) PutMovieEdition(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", r.PathValue("uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutMovieEdition(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("PUT "+options.BaseURL+"/sources/{discUuid}/disc/file/{fileUuid}", wrapper.AddFileToDisc)
	m.HandleFunc("GET "+options.BaseURL+"/sources/{uuid}", wrapper.GetSource)
	m.HandleFunc("PUT "+options.BaseURL+"/sources/{uuid}/disc", wrapper.PutDiscSource)
	m.HandleFunc("PUT "+options.BaseURL+"/sources/{uuid}/disc/all_files_added", wrapper.MarkDiscAllFilesAdded)
	m.HandleFunc("PUT "+options.BaseURL+"/sources/{uuid}/file", wrapper.PutFileSource)
	m.HandleFunc("PUT "+options.BaseURL+"/works/{movieUuid}/movie/editions/{editionUuid}", wrapper.AddEditionToMovie)
	m.HandleFunc("GET "+options.BaseURL+"/works/{uuid}", wrapper.GetWork)
	m.HandleFunc("PUT "+options.BaseURL+"/works/{uuid}/movie", wrapper.PutMovieWork)
	m.HandleFunc("PUT "+options.BaseURL+"/works/{uuid}/movie_edition", wrapper.PutMovieEdition)

	return m
}

type AddFileToDiscRequestObject struct {
	DiscUuid openapi_types.UUID `json:"discUuid"`
	FileUuid openapi_types.UUID `json:"fileUuid"`
}

type AddFileToDiscResponseObject interface {
	VisitAddFileToDiscResponse(w http.ResponseWriter) error
}

type AddFileToDisc201JSONResponse Source

func (response AddFileToDisc201JSONResponse) VisitAddFileToDiscResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type AddFileToDisc400JSONResponse Error

func (response AddFileToDisc400JSONResponse) VisitAddFileToDiscResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type AddFileToDisc404JSONResponse Error

func (response AddFileToDisc404JSONResponse) VisitAddFileToDiscResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type AddFileToDisc500JSONResponse Error

func (response AddFileToDisc500JSONResponse) VisitAddFileToDiscResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetSourceRequestObject struct {
	Uuid openapi_types.UUID `json:"uuid"`
}

type GetSourceResponseObject interface {
	VisitGetSourceResponse(w http.ResponseWriter) error
}

type GetSource200JSONResponse Source

func (response GetSource200JSONResponse) VisitGetSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSource400JSONResponse Error

func (response GetSource400JSONResponse) VisitGetSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetSource404JSONResponse Error

func (response GetSource404JSONResponse) VisitGetSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetSource500JSONResponse Error

func (response GetSource500JSONResponse) VisitGetSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PutDiscSourceRequestObject struct {
	Uuid openapi_types.UUID `json:"uuid"`
	Body *PutDiscSourceJSONRequestBody
}

type PutDiscSourceResponseObject interface {
	VisitPutDiscSourceResponse(w http.ResponseWriter) error
}

type PutDiscSource200Response struct {
}

func (response PutDiscSource200Response) VisitPutDiscSourceResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type PutDiscSource201Response struct {
}

func (response PutDiscSource201Response) VisitPutDiscSourceResponse(w http.ResponseWriter) error {
	w.WriteHeader(201)
	return nil
}

type PutDiscSource400JSONResponse Error

func (response PutDiscSource400JSONResponse) VisitPutDiscSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PutDiscSource409JSONResponse Error

func (response PutDiscSource409JSONResponse) VisitPutDiscSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type PutDiscSource500JSONResponse Error

func (response PutDiscSource500JSONResponse) VisitPutDiscSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type MarkDiscAllFilesAddedRequestObject struct {
	Uuid openapi_types.UUID `json:"uuid"`
}

type MarkDiscAllFilesAddedResponseObject interface {
	VisitMarkDiscAllFilesAddedResponse(w http.ResponseWriter) error
}

type MarkDiscAllFilesAdded200JSONResponse Source

func (response MarkDiscAllFilesAdded200JSONResponse) VisitMarkDiscAllFilesAddedResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type MarkDiscAllFilesAdded404JSONResponse Error

func (response MarkDiscAllFilesAdded404JSONResponse) VisitMarkDiscAllFilesAddedResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type MarkDiscAllFilesAdded500JSONResponse Error

func (response MarkDiscAllFilesAdded500JSONResponse) VisitMarkDiscAllFilesAddedResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PutFileSourceRequestObject struct {
	Uuid openapi_types.UUID `json:"uuid"`
	Body *PutFileSourceJSONRequestBody
}

type PutFileSourceResponseObject interface {
	VisitPutFileSourceResponse(w http.ResponseWriter) error
}

type PutFileSource200Response struct {
}

func (response PutFileSource200Response) VisitPutFileSourceResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type PutFileSource201Response struct {
}

func (response PutFileSource201Response) VisitPutFileSourceResponse(w http.ResponseWriter) error {
	w.WriteHeader(201)
	return nil
}

type PutFileSource400JSONResponse Error

func (response PutFileSource400JSONResponse) VisitPutFileSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PutFileSource409JSONResponse Error

func (response PutFileSource409JSONResponse) VisitPutFileSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type PutFileSource500JSONResponse Error

func (response PutFileSource500JSONResponse) VisitPutFileSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type AddEditionToMovieRequestObject struct {
	MovieUuid   openapi_types.UUID `json:"movieUuid"`
	EditionUuid openapi_types.UUID `json:"editionUuid"`
}

type AddEditionToMovieResponseObject interface {
	VisitAddEditionToMovieResponse(w http.ResponseWriter) error
}

type AddEditionToMovie200Response struct {
}

func (response AddEditionToMovie200Response) VisitAddEditionToMovieResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type AddEditionToMovie400JSONResponse Error

func (response AddEditionToMovie400JSONResponse) VisitAddEditionToMovieResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type AddEditionToMovie404JSONResponse Error

func (response AddEditionToMovie404JSONResponse) VisitAddEditionToMovieResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type AddEditionToMovie500JSONResponse Error

func (response AddEditionToMovie500JSONResponse) VisitAddEditionToMovieResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkRequestObject struct {
	Uuid openapi_types.UUID `json:"uuid"`
}

type GetWorkResponseObject interface {
	VisitGetWorkResponse(w http.ResponseWriter) error
}

type GetWork200JSONResponse Work

func (response GetWork200JSONResponse) VisitGetWorkResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetWork400JSONResponse Error

func (response GetWork400JSONResponse) VisitGetWorkResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetWork404JSONResponse Error

func (response GetWork404JSONResponse) VisitGetWorkResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetWork500JSONResponse Error

func (response GetWork500JSONResponse) VisitGetWorkResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PutMovieWorkRequestObject struct {
	Uuid openapi_types.UUID `json:"uuid"`
	Body *PutMovieWorkJSONRequestBody
}

type PutMovieWorkResponseObject interface {
	VisitPutMovieWorkResponse(w http.ResponseWriter) error
}

type PutMovieWork200Response struct {
}

func (response PutMovieWork200Response) VisitPutMovieWorkResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type PutMovieWork201Response struct {
}

func (response PutMovieWork201Response) VisitPutMovieWorkResponse(w http.ResponseWriter) error {
	w.WriteHeader(201)
	return nil
}

type PutMovieWork400JSONResponse Error

func (response PutMovieWork400JSONResponse) VisitPutMovieWorkResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PutMovieWork409JSONResponse Error

func (response PutMovieWork409JSONResponse) VisitPutMovieWorkResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type PutMovieWork500JSONResponse Error

func (response PutMovieWork500JSONResponse) VisitPutMovieWorkResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PutMovieEditionRequestObject struct {
	Uuid openapi_types.UUID `json:"uuid"`
	Body *PutMovieEditionJSONRequestBody
}

type PutMovieEditionResponseObject interface {
	VisitPutMovieEditionResponse(w http.ResponseWriter) error
}

type PutMovieEdition200Response struct {
}

func (response PutMovieEdition200Response) VisitPutMovieEditionResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type PutMovieEdition201Response struct {
}

func (response PutMovieEdition201Response) VisitPutMovieEditionResponse(w http.ResponseWriter) error {
	w.WriteHeader(201)
	return nil
}

type PutMovieEdition400JSONResponse Error

func (response PutMovieEdition400JSONResponse) VisitPutMovieEditionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PutMovieEdition409JSONResponse Error

func (response PutMovieEdition409JSONResponse) VisitPutMovieEditionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type PutMovieEdition500JSONResponse Error

func (response PutMovieEdition500JSONResponse) VisitPutMovieEditionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Associates a file source with a disc source
	// (PUT /sources/{discUuid}/disc/file/{fileUuid})
	AddFileToDisc(ctx context.Context, request AddFileToDiscRequestObject) (AddFileToDiscResponseObject, error)
	// Get a source by UUID
	// (GET /sources/{uuid})
	GetSource(ctx context.Context, request GetSourceRequestObject) (GetSourceResponseObject, error)
	// Add a disc source with the given UUID.
	// (PUT /sources/{uuid}/disc)
	PutDiscSource(ctx context.Context, request PutDiscSourceRequestObject) (PutDiscSourceResponseObject, error)
	// Mark all files from the disc source as added
	// (PUT /sources/{uuid}/disc/all_files_added)
	MarkDiscAllFilesAdded(ctx context.Context, request MarkDiscAllFilesAddedRequestObject) (MarkDiscAllFilesAddedResponseObject, error)
	// Add a file source with the given UUID.
	// (PUT /sources/{uuid}/file)
	PutFileSource(ctx context.Context, request PutFileSourceRequestObject) (PutFileSourceResponseObject, error)
	// Associate an existing movie edition with a movie work.
	// (PUT /works/{movieUuid}/movie/editions/{editionUuid})
	AddEditionToMovie(ctx context.Context, request AddEditionToMovieRequestObject) (AddEditionToMovieResponseObject, error)
	// Get a work by UUID
	// (GET /works/{uuid})
	GetWork(ctx context.Context, request GetWorkRequestObject) (GetWorkResponseObject, error)
	// Add a movie work with the given uuid.
	// (PUT /works/{uuid}/movie)
	PutMovieWork(ctx context.Context, request PutMovieWorkRequestObject) (PutMovieWorkResponseObject, error)
	// Create a new movie edition work with the given uuid.
	// (PUT /works/{uuid}/movie_edition)
	PutMovieEdition(ctx context.Context, request PutMovieEditionRequestObject) (PutMovieEditionResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// AddFileToDisc operation middleware
func (sh *strictHandler) AddFileToDisc(w http.ResponseWriter, r *http.Request, discUuid openapi_types.UUID, fileUuid openapi_types.UUID) {
	var request AddFileToDiscRequestObject

	request.DiscUuid = discUuid
	request.FileUuid = fileUuid

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AddFileToDisc(ctx, request.(AddFileToDiscRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AddFileToDisc")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AddFileToDiscResponseObject); ok {
		if err := validResponse.VisitAddFileToDiscResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSource operation middleware
func (sh *strictHandler) GetSource(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	var request GetSourceRequestObject

	request.Uuid = uuid

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSource(ctx, request.(GetSourceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSource")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSourceResponseObject); ok {
		if err := validResponse.VisitGetSourceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutDiscSource operation middleware
func (sh *strictHandler) PutDiscSource(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	var request PutDiscSourceRequestObject

	request.Uuid = uuid

	var body PutDiscSourceJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutDiscSource(ctx, request.(PutDiscSourceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutDiscSource")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutDiscSourceResponseObject); ok {
		if err := validResponse.VisitPutDiscSourceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// MarkDiscAllFilesAdded operation middleware
func (sh *strictHandler) MarkDiscAllFilesAdded(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	var request MarkDiscAllFilesAddedRequestObject

	request.Uuid = uuid

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.MarkDiscAllFilesAdded(ctx, request.(MarkDiscAllFilesAddedRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "MarkDiscAllFilesAdded")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(MarkDiscAllFilesAddedResponseObject); ok {
		if err := validResponse.VisitMarkDiscAllFilesAddedResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutFileSource operation middleware
func (sh *strictHandler) PutFileSource(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	var request PutFileSourceRequestObject

	request.Uuid = uuid

	var body PutFileSourceJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutFileSource(ctx, request.(PutFileSourceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutFileSource")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutFileSourceResponseObject); ok {
		if err := validResponse.VisitPutFileSourceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AddEditionToMovie operation middleware
func (sh *strictHandler) AddEditionToMovie(w http.ResponseWriter, r *http.Request, movieUuid openapi_types.UUID, editionUuid openapi_types.UUID) {
	var request AddEditionToMovieRequestObject

	request.MovieUuid = movieUuid
	request.EditionUuid = editionUuid

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AddEditionToMovie(ctx, request.(AddEditionToMovieRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AddEditionToMovie")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AddEditionToMovieResponseObject); ok {
		if err := validResponse.VisitAddEditionToMovieResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetWork operation middleware
func (sh *strictHandler) GetWork(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	var request GetWorkRequestObject

	request.Uuid = uuid

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetWork(ctx, request.(GetWorkRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetWork")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetWorkResponseObject); ok {
		if err := validResponse.VisitGetWorkResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutMovieWork operation middleware
func (sh *strictHandler) PutMovieWork(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	var request PutMovieWorkRequestObject

	request.Uuid = uuid

	var body PutMovieWorkJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutMovieWork(ctx, request.(PutMovieWorkRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutMovieWork")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutMovieWorkResponseObject); ok {
		if err := validResponse.VisitPutMovieWorkResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutMovieEdition operation middleware
func (sh *strictHandler) PutMovieEdition(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	var request PutMovieEditionRequestObject

	request.Uuid = uuid

	var body PutMovieEditionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutMovieEdition(ctx, request.(PutMovieEditionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutMovieEdition")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutMovieEditionResponseObject); ok {
		if err := validResponse.VisitPutMovieEditionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xabW/bOBL+KwTvgNsFFMt2nLTrb716u/CHtIvGueLQFgEtjW02EqmSlFMj8H9fkNSr",
	"RVt2kgYOmi+JYZOc4cwzz7xIdzjgccIZMCXx8A7LYAExMR9HVAb6fwgyEDRRlDM8xCNQhEYSkSlPFSIo",
	"pDJAkqcigA5CYxZEaQghojOkFpD9gKjMVnawhxPBExCKgpFCougdjUC+CUMIm+LGLKQBUSDR7QLUAgQi",
	"UYRmegeaCR4bKUaHBVkCmgIwRMxRHoYfJE4iwEMlUvCwWiWAh3jKeQSE4bWHuaDzERXvSQxNyR8EnVNG",
	"IhRSAYHiYoUYiQHxWSGzKgNfrLTBRvliXAiUSlA21/ISohZNQeb6K6kgRnqBvqiA8l5UoohrE9SuhH1G",
	"pB9DSInfKnntYQHfUyq0hT/Xrp0p5W344WtxBp9+g0Bp7f8Uggutft2BAQ8d1jOLkfmtqvX7D5Prdx+u",
	"3o9c5olBSjLfelj+c/W8j5AhjHGFZjxlYevt82NcV9QWaIe8Rl8B+V2I1wubiN8PBRnM9BF7+t2P+ZJC",
	"J75ZttrAqOAywIU+YrsFZAIBndEAKY6MNHTLxY10BL7+3hrBatWwgoAIiIT/AxFNeR/tj2gFROSWMOdU",
	"TdHv9rrFFShTMAeh76Cocnlxor/eehgeswDsUgcyVRxOxw52miwAGZOhEVFkqlX+bXIxmv6OaAhM0RkF",
	"gWZcbLnAq373rHmDDV/Z62x11p8htcq0obbwHdgd2hS5d7b4b0EKB+a7mo7MfpgY7RoGWiV1mxfSf4PO",
	"vOOhLzjH738kepuqL1h/N1kAUYIGJPqCf6+5qb66FehV5VwmvDTR2iS1MMt9/xYww0P8L7/Mkn6WIn2T",
	"H9cenmWksWutIZa1h9OUOmB0xej3FFyYsWxSs0C/fwqDs/NXJ/D6j+lJrx+enpDB2fnJoH9+3hv0Xg26",
	"3R728IyLmCg8tCIdmNYevkppKB2pz3wgESJCkJX2n4HD1dV4JBGRkgdU5yN0S9UCqQWVDj0/4167ol3s",
	"4UH7slPtO6ogNrq23iz7wijfQITZ5ILCJy5umkCIc0Lc5V3LmjqDbURk66Z87drD1oR7eyTLMzt8on1W",
	"98ie0DltX9Z/iEcOD4PNq+yLrRbF9oOGXkbZjDcVfvP32KgYE0bmlM3RkobAbU5EhIWZkyQukhL+n1nx",
	"ligS8Tm6BLGkJm6WIKQ9tNfpdrqmOk2AkYTiIT7tdDunWalmDO5nB/t3mqg0Zta+/uRrLvLv9F/zpcFz",
	"qhyah2FeoJT2DtF0hfK9OsUXNWhe1NRW5qKxUVUQfbROkvpwzXcTPrI1ckIEiUGBkHj4ueH0q/GoWlOX",
	"VEL1z1l1ykyJjisiS8fZ6t6G1R5oXHu7VDAWUVz3EG4Vcvs8SIWverNMOJOWZfrdni2lmQJm3EWSJNKN",
	"D+XM/yYtm5Tn7+KVLKUZ2DZLTNscIZkGAUg5S6PIBOSg2300BWyf4JA/ZksS0RBpu4FUVu7g58vVMERc",
	"oHdl3V7pF9YePnua2ysQmsIliCUIBNlCD8s0jolY6cjJeVzW2wzL6rVm2+wseSDNw30OylVPq1QwfahF",
	"B7LcVvDrnC6BmVzSCOa/QF3mEbl3IGdaK44EKEFhuSWe08cPpO4TBNJlET0ol/7kQWTMnZnnqQLp8phj",
	"5y8wXY5VcbqyaHYEiZ/X9rsS4/as1xIuf6dK083hIVOVuCv/PE7IGAL+Lw9XB/muXhq/TM/y6Zm7Zqy7",
	"aO1mKkemykCQJqEp6DdTdVYrbN94bBn+jycjprL3MZFFIgEkXCH4QaWyBTmVhr3yYfRR5f4w3CCe7DpV",
	"vulsZTSfRNG1mYtfk3yU7mS4C2K6ky1T9D04DxFZjNjr5KeP1kh8U5slP2YD8EwLBhOe1twxETcQFjZ0",
	"xOmvnsg1itrwWUDQFQ75QK61871ngtfYPjzBVyU+jwR/vA8q7pleqw3gQem1uvElve6RXu2Tr+NLr42e",
	"2plezQDPvzMwtcM189HPniZI/y771DJkq3TzzJqJsvnGc5A6+VTOLfUrn7RtrC4U7LhmcNlsecIvsgdP",
	"e1NVKdBNUYXcnzeHqxtJ82VuTLdKFcP9jPpgo4SqKVcZvv9SY7WLEpZcFNY48sHajkjMZmwl+OtssO+E",
	"7ZMxyCHztU820PYOT2Py5z1bM1d+mawVsg1ojnmuZjBXm6pVw8IvHpPuqrm35rH2kttwzX3j5BmU2i9v",
	"wzzwbZh7dgSVHHZQQ2D3/YKtgCGqAxqB7O2v4+sEKmS00QikpqDewnHXUL7d4eS6twJMmYEY3LoKjE05",
	"28gufzPkHnx3u6DBwlFF39IoQlMohndHzYjP+LWyB3FRfpF70FHRkLzQ0l60VL7TeEz0tItAdrCVPsMc",
	"6mKJESwh4kkMTGWisYdTEeEhXiiVDH0/4gGJFlyq4evu6y5ef13/EwAA///bPYB3GjAAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
