//go:build go1.22

// Package vcrest provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package vcrest

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Disc Details about a disc source.  Included if the source is a disc.
type Disc struct {
	// AllFilesAdded Indicates whether all files from the disc have been added
	AllFilesAdded bool `json:"allFilesAdded"`

	// OrigDirName Original directory name of the disc
	OrigDirName string `json:"origDirName"`

	// Path Filesystem path where the disc is located
	Path string `json:"path"`
}

// Error defines model for Error.
type Error struct {
	// Code Error code
	Code *string `json:"code,omitempty"`

	// Message Error message
	Message string `json:"message"`
}

// File Details about a file source. Included if the source is a file.
type File struct {
	// Path Filesystem path of the file
	Path string `json:"path"`
}

// Movie Details specific to movie works.  Included if the work is a movie.
type Movie struct {
	// ReleaseYear Release year of the movie
	ReleaseYear *int `json:"releaseYear,omitempty"`

	// Title Title of the movie
	Title string `json:"title"`

	// TmdbId The Movie Database (TMDb) identifier for the movie
	TmdbId *int `json:"tmdbId,omitempty"`
}

// MovieEdition Details about a specific edition of a movie.  Included if the work has a movie edition.
type MovieEdition struct {
	// EditionType Type of the movie edition (e.g., "Director's Cut", "Theatrical")
	EditionType string `json:"editionType"`
}

// Source defines model for Source.
type Source struct {
	// Disc Details about a disc source.  Included if the source is a disc.
	Disc *Disc `json:"disc,omitempty"`

	// File Details about a file source. Included if the source is a file.
	File *File `json:"file,omitempty"`

	// Uuid Unique identifier for the source
	Uuid openapi_types.UUID `json:"uuid"`

	// WorkUuids Optional array of work UUIDs associated with this source
	WorkUuids []openapi_types.UUID `json:"workUuids,omitempty"`
}

// Work defines model for Work.
type Work struct {
	// Movie Details specific to movie works.  Included if the work is a movie.
	Movie *Movie `json:"movie,omitempty"`

	// MovieEdition Details about a specific edition of a movie.  Included if the work has a movie edition.
	MovieEdition *MovieEdition `json:"movieEdition,omitempty"`

	// SourceUuids Optional array of source UUIDs associated with this work
	SourceUuids []openapi_types.UUID `json:"sourceUuids,omitempty"`

	// Uuid Unique identifier for the work
	Uuid openapi_types.UUID `json:"uuid"`
}

// AddDiscSourceJSONBody defines parameters for AddDiscSource.
type AddDiscSourceJSONBody struct {
	// OrigDirName Original directory name of the disc
	OrigDirName string `json:"origDirName"`

	// Path Filesystem path where the disc is located
	Path string `json:"path"`
}

// AddFileSourceJSONBody defines parameters for AddFileSource.
type AddFileSourceJSONBody struct {
	// Path Filesystem path of the file
	Path string `json:"path"`
}

// AddMovieWorkJSONBody defines parameters for AddMovieWork.
type AddMovieWorkJSONBody struct {
	// ReleaseYear Release year of the movie
	ReleaseYear *int `json:"releaseYear,omitempty"`

	// Title Title of the movie
	Title string `json:"title"`

	// TmdbId The Movie Database (TMDb) identifier for the movie
	TmdbId *int `json:"tmdbId,omitempty"`
}

// AddMovieEditionJSONBody defines parameters for AddMovieEdition.
type AddMovieEditionJSONBody struct {
	// EditionType Type of the movie edition (e.g., "Director's Cut", "Theatrical")
	EditionType string `json:"editionType"`
}

// AddDiscSourceJSONRequestBody defines body for AddDiscSource for application/json ContentType.
type AddDiscSourceJSONRequestBody AddDiscSourceJSONBody

// AddFileSourceJSONRequestBody defines body for AddFileSource for application/json ContentType.
type AddFileSourceJSONRequestBody AddFileSourceJSONBody

// AddMovieWorkJSONRequestBody defines body for AddMovieWork for application/json ContentType.
type AddMovieWorkJSONRequestBody AddMovieWorkJSONBody

// AddMovieEditionJSONRequestBody defines body for AddMovieEdition for application/json ContentType.
type AddMovieEditionJSONRequestBody AddMovieEditionJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// AddFileToDisc request
	AddFileToDisc(ctx context.Context, discUuid openapi_types.UUID, fileUuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetSource request
	GetSource(ctx context.Context, uuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AddDiscSourceWithBody request with any body
	AddDiscSourceWithBody(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	AddDiscSource(ctx context.Context, uuid openapi_types.UUID, body AddDiscSourceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// MarkDiscAllFilesAdded request
	MarkDiscAllFilesAdded(ctx context.Context, uuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AddFileSourceWithBody request with any body
	AddFileSourceWithBody(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	AddFileSource(ctx context.Context, uuid openapi_types.UUID, body AddFileSourceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AddEditionToMovie request
	AddEditionToMovie(ctx context.Context, movieUuid openapi_types.UUID, editionUuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetWork request
	GetWork(ctx context.Context, uuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AddMovieWorkWithBody request with any body
	AddMovieWorkWithBody(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	AddMovieWork(ctx context.Context, uuid openapi_types.UUID, body AddMovieWorkJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AddMovieEditionWithBody request with any body
	AddMovieEditionWithBody(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	AddMovieEdition(ctx context.Context, uuid openapi_types.UUID, body AddMovieEditionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) AddFileToDisc(ctx context.Context, discUuid openapi_types.UUID, fileUuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddFileToDiscRequest(c.Server, discUuid, fileUuid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetSource(ctx context.Context, uuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSourceRequest(c.Server, uuid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AddDiscSourceWithBody(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddDiscSourceRequestWithBody(c.Server, uuid, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AddDiscSource(ctx context.Context, uuid openapi_types.UUID, body AddDiscSourceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddDiscSourceRequest(c.Server, uuid, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) MarkDiscAllFilesAdded(ctx context.Context, uuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewMarkDiscAllFilesAddedRequest(c.Server, uuid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AddFileSourceWithBody(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddFileSourceRequestWithBody(c.Server, uuid, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AddFileSource(ctx context.Context, uuid openapi_types.UUID, body AddFileSourceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddFileSourceRequest(c.Server, uuid, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AddEditionToMovie(ctx context.Context, movieUuid openapi_types.UUID, editionUuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddEditionToMovieRequest(c.Server, movieUuid, editionUuid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetWork(ctx context.Context, uuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetWorkRequest(c.Server, uuid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AddMovieWorkWithBody(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddMovieWorkRequestWithBody(c.Server, uuid, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AddMovieWork(ctx context.Context, uuid openapi_types.UUID, body AddMovieWorkJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddMovieWorkRequest(c.Server, uuid, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AddMovieEditionWithBody(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddMovieEditionRequestWithBody(c.Server, uuid, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AddMovieEdition(ctx context.Context, uuid openapi_types.UUID, body AddMovieEditionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAddMovieEditionRequest(c.Server, uuid, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewAddFileToDiscRequest generates requests for AddFileToDisc
func NewAddFileToDiscRequest(server string, discUuid openapi_types.UUID, fileUuid openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "discUuid", runtime.ParamLocationPath, discUuid)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "fileUuid", runtime.ParamLocationPath, fileUuid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sources/%s/disc/file/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetSourceRequest generates requests for GetSource
func NewGetSourceRequest(server string, uuid openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "uuid", runtime.ParamLocationPath, uuid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sources/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewAddDiscSourceRequest calls the generic AddDiscSource builder with application/json body
func NewAddDiscSourceRequest(server string, uuid openapi_types.UUID, body AddDiscSourceJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAddDiscSourceRequestWithBody(server, uuid, "application/json", bodyReader)
}

// NewAddDiscSourceRequestWithBody generates requests for AddDiscSource with any type of body
func NewAddDiscSourceRequestWithBody(server string, uuid openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "uuid", runtime.ParamLocationPath, uuid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sources/%s/disc", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewMarkDiscAllFilesAddedRequest generates requests for MarkDiscAllFilesAdded
func NewMarkDiscAllFilesAddedRequest(server string, uuid openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "uuid", runtime.ParamLocationPath, uuid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sources/%s/disc/all_files_added", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewAddFileSourceRequest calls the generic AddFileSource builder with application/json body
func NewAddFileSourceRequest(server string, uuid openapi_types.UUID, body AddFileSourceJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAddFileSourceRequestWithBody(server, uuid, "application/json", bodyReader)
}

// NewAddFileSourceRequestWithBody generates requests for AddFileSource with any type of body
func NewAddFileSourceRequestWithBody(server string, uuid openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "uuid", runtime.ParamLocationPath, uuid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/sources/%s/file", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewAddEditionToMovieRequest generates requests for AddEditionToMovie
func NewAddEditionToMovieRequest(server string, movieUuid openapi_types.UUID, editionUuid openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "movieUuid", runtime.ParamLocationPath, movieUuid)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "editionUuid", runtime.ParamLocationPath, editionUuid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/works/%s/movie/editions/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetWorkRequest generates requests for GetWork
func NewGetWorkRequest(server string, uuid openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "uuid", runtime.ParamLocationPath, uuid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/works/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewAddMovieWorkRequest calls the generic AddMovieWork builder with application/json body
func NewAddMovieWorkRequest(server string, uuid openapi_types.UUID, body AddMovieWorkJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAddMovieWorkRequestWithBody(server, uuid, "application/json", bodyReader)
}

// NewAddMovieWorkRequestWithBody generates requests for AddMovieWork with any type of body
func NewAddMovieWorkRequestWithBody(server string, uuid openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "uuid", runtime.ParamLocationPath, uuid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/works/%s/movie", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewAddMovieEditionRequest calls the generic AddMovieEdition builder with application/json body
func NewAddMovieEditionRequest(server string, uuid openapi_types.UUID, body AddMovieEditionJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAddMovieEditionRequestWithBody(server, uuid, "application/json", bodyReader)
}

// NewAddMovieEditionRequestWithBody generates requests for AddMovieEdition with any type of body
func NewAddMovieEditionRequestWithBody(server string, uuid openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "uuid", runtime.ParamLocationPath, uuid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/works/%s/movie_edition", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// AddFileToDiscWithResponse request
	AddFileToDiscWithResponse(ctx context.Context, discUuid openapi_types.UUID, fileUuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*AddFileToDiscResponse, error)

	// GetSourceWithResponse request
	GetSourceWithResponse(ctx context.Context, uuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetSourceResponse, error)

	// AddDiscSourceWithBodyWithResponse request with any body
	AddDiscSourceWithBodyWithResponse(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AddDiscSourceResponse, error)

	AddDiscSourceWithResponse(ctx context.Context, uuid openapi_types.UUID, body AddDiscSourceJSONRequestBody, reqEditors ...RequestEditorFn) (*AddDiscSourceResponse, error)

	// MarkDiscAllFilesAddedWithResponse request
	MarkDiscAllFilesAddedWithResponse(ctx context.Context, uuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*MarkDiscAllFilesAddedResponse, error)

	// AddFileSourceWithBodyWithResponse request with any body
	AddFileSourceWithBodyWithResponse(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AddFileSourceResponse, error)

	AddFileSourceWithResponse(ctx context.Context, uuid openapi_types.UUID, body AddFileSourceJSONRequestBody, reqEditors ...RequestEditorFn) (*AddFileSourceResponse, error)

	// AddEditionToMovieWithResponse request
	AddEditionToMovieWithResponse(ctx context.Context, movieUuid openapi_types.UUID, editionUuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*AddEditionToMovieResponse, error)

	// GetWorkWithResponse request
	GetWorkWithResponse(ctx context.Context, uuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetWorkResponse, error)

	// AddMovieWorkWithBodyWithResponse request with any body
	AddMovieWorkWithBodyWithResponse(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AddMovieWorkResponse, error)

	AddMovieWorkWithResponse(ctx context.Context, uuid openapi_types.UUID, body AddMovieWorkJSONRequestBody, reqEditors ...RequestEditorFn) (*AddMovieWorkResponse, error)

	// AddMovieEditionWithBodyWithResponse request with any body
	AddMovieEditionWithBodyWithResponse(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AddMovieEditionResponse, error)

	AddMovieEditionWithResponse(ctx context.Context, uuid openapi_types.UUID, body AddMovieEditionJSONRequestBody, reqEditors ...RequestEditorFn) (*AddMovieEditionResponse, error)
}

type AddFileToDiscResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *Source
	JSON400      *Error
	JSON404      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r AddFileToDiscResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AddFileToDiscResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetSourceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Source
	JSON400      *Error
	JSON404      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r GetSourceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSourceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type AddDiscSourceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *Error
	JSON409      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r AddDiscSourceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AddDiscSourceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type MarkDiscAllFilesAddedResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Source
	JSON404      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r MarkDiscAllFilesAddedResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r MarkDiscAllFilesAddedResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type AddFileSourceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *Error
	JSON409      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r AddFileSourceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AddFileSourceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type AddEditionToMovieResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *Error
	JSON404      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r AddEditionToMovieResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AddEditionToMovieResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetWorkResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Work
	JSON400      *Error
	JSON404      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r GetWorkResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetWorkResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type AddMovieWorkResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *Error
	JSON409      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r AddMovieWorkResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AddMovieWorkResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type AddMovieEditionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *Error
	JSON409      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r AddMovieEditionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AddMovieEditionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// AddFileToDiscWithResponse request returning *AddFileToDiscResponse
func (c *ClientWithResponses) AddFileToDiscWithResponse(ctx context.Context, discUuid openapi_types.UUID, fileUuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*AddFileToDiscResponse, error) {
	rsp, err := c.AddFileToDisc(ctx, discUuid, fileUuid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAddFileToDiscResponse(rsp)
}

// GetSourceWithResponse request returning *GetSourceResponse
func (c *ClientWithResponses) GetSourceWithResponse(ctx context.Context, uuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetSourceResponse, error) {
	rsp, err := c.GetSource(ctx, uuid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSourceResponse(rsp)
}

// AddDiscSourceWithBodyWithResponse request with arbitrary body returning *AddDiscSourceResponse
func (c *ClientWithResponses) AddDiscSourceWithBodyWithResponse(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AddDiscSourceResponse, error) {
	rsp, err := c.AddDiscSourceWithBody(ctx, uuid, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAddDiscSourceResponse(rsp)
}

func (c *ClientWithResponses) AddDiscSourceWithResponse(ctx context.Context, uuid openapi_types.UUID, body AddDiscSourceJSONRequestBody, reqEditors ...RequestEditorFn) (*AddDiscSourceResponse, error) {
	rsp, err := c.AddDiscSource(ctx, uuid, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAddDiscSourceResponse(rsp)
}

// MarkDiscAllFilesAddedWithResponse request returning *MarkDiscAllFilesAddedResponse
func (c *ClientWithResponses) MarkDiscAllFilesAddedWithResponse(ctx context.Context, uuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*MarkDiscAllFilesAddedResponse, error) {
	rsp, err := c.MarkDiscAllFilesAdded(ctx, uuid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseMarkDiscAllFilesAddedResponse(rsp)
}

// AddFileSourceWithBodyWithResponse request with arbitrary body returning *AddFileSourceResponse
func (c *ClientWithResponses) AddFileSourceWithBodyWithResponse(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AddFileSourceResponse, error) {
	rsp, err := c.AddFileSourceWithBody(ctx, uuid, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAddFileSourceResponse(rsp)
}

func (c *ClientWithResponses) AddFileSourceWithResponse(ctx context.Context, uuid openapi_types.UUID, body AddFileSourceJSONRequestBody, reqEditors ...RequestEditorFn) (*AddFileSourceResponse, error) {
	rsp, err := c.AddFileSource(ctx, uuid, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAddFileSourceResponse(rsp)
}

// AddEditionToMovieWithResponse request returning *AddEditionToMovieResponse
func (c *ClientWithResponses) AddEditionToMovieWithResponse(ctx context.Context, movieUuid openapi_types.UUID, editionUuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*AddEditionToMovieResponse, error) {
	rsp, err := c.AddEditionToMovie(ctx, movieUuid, editionUuid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAddEditionToMovieResponse(rsp)
}

// GetWorkWithResponse request returning *GetWorkResponse
func (c *ClientWithResponses) GetWorkWithResponse(ctx context.Context, uuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetWorkResponse, error) {
	rsp, err := c.GetWork(ctx, uuid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetWorkResponse(rsp)
}

// AddMovieWorkWithBodyWithResponse request with arbitrary body returning *AddMovieWorkResponse
func (c *ClientWithResponses) AddMovieWorkWithBodyWithResponse(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AddMovieWorkResponse, error) {
	rsp, err := c.AddMovieWorkWithBody(ctx, uuid, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAddMovieWorkResponse(rsp)
}

func (c *ClientWithResponses) AddMovieWorkWithResponse(ctx context.Context, uuid openapi_types.UUID, body AddMovieWorkJSONRequestBody, reqEditors ...RequestEditorFn) (*AddMovieWorkResponse, error) {
	rsp, err := c.AddMovieWork(ctx, uuid, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAddMovieWorkResponse(rsp)
}

// AddMovieEditionWithBodyWithResponse request with arbitrary body returning *AddMovieEditionResponse
func (c *ClientWithResponses) AddMovieEditionWithBodyWithResponse(ctx context.Context, uuid openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AddMovieEditionResponse, error) {
	rsp, err := c.AddMovieEditionWithBody(ctx, uuid, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAddMovieEditionResponse(rsp)
}

func (c *ClientWithResponses) AddMovieEditionWithResponse(ctx context.Context, uuid openapi_types.UUID, body AddMovieEditionJSONRequestBody, reqEditors ...RequestEditorFn) (*AddMovieEditionResponse, error) {
	rsp, err := c.AddMovieEdition(ctx, uuid, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAddMovieEditionResponse(rsp)
}

// ParseAddFileToDiscResponse parses an HTTP response from a AddFileToDiscWithResponse call
func ParseAddFileToDiscResponse(rsp *http.Response) (*AddFileToDiscResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AddFileToDiscResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Source
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetSourceResponse parses an HTTP response from a GetSourceWithResponse call
func ParseGetSourceResponse(rsp *http.Response) (*GetSourceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSourceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Source
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseAddDiscSourceResponse parses an HTTP response from a AddDiscSourceWithResponse call
func ParseAddDiscSourceResponse(rsp *http.Response) (*AddDiscSourceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AddDiscSourceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseMarkDiscAllFilesAddedResponse parses an HTTP response from a MarkDiscAllFilesAddedWithResponse call
func ParseMarkDiscAllFilesAddedResponse(rsp *http.Response) (*MarkDiscAllFilesAddedResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &MarkDiscAllFilesAddedResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Source
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseAddFileSourceResponse parses an HTTP response from a AddFileSourceWithResponse call
func ParseAddFileSourceResponse(rsp *http.Response) (*AddFileSourceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AddFileSourceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseAddEditionToMovieResponse parses an HTTP response from a AddEditionToMovieWithResponse call
func ParseAddEditionToMovieResponse(rsp *http.Response) (*AddEditionToMovieResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AddEditionToMovieResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetWorkResponse parses an HTTP response from a GetWorkWithResponse call
func ParseGetWorkResponse(rsp *http.Response) (*GetWorkResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetWorkResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Work
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseAddMovieWorkResponse parses an HTTP response from a AddMovieWorkWithResponse call
func ParseAddMovieWorkResponse(rsp *http.Response) (*AddMovieWorkResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AddMovieWorkResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseAddMovieEditionResponse parses an HTTP response from a AddMovieEditionWithResponse call
func ParseAddMovieEditionResponse(rsp *http.Response) (*AddMovieEditionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AddMovieEditionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Associates a file source with a disc source
	// (PUT /sources/{discUuid}/disc/file/{fileUuid})
	AddFileToDisc(w http.ResponseWriter, r *http.Request, discUuid openapi_types.UUID, fileUuid openapi_types.UUID)
	// Get a source by UUID
	// (GET /sources/{uuid})
	GetSource(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID)
	// Add a disc source with the given UUID.
	// (PUT /sources/{uuid}/disc)
	AddDiscSource(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID)
	// Mark all files from the disc source as added
	// (PUT /sources/{uuid}/disc/all_files_added)
	MarkDiscAllFilesAdded(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID)
	// Add a file source with the given UUID.
	// (PUT /sources/{uuid}/file)
	AddFileSource(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID)
	// Associate an existing movie edition with a movie work.
	// (PUT /works/{movieUuid}/movie/editions/{editionUuid})
	AddEditionToMovie(w http.ResponseWriter, r *http.Request, movieUuid openapi_types.UUID, editionUuid openapi_types.UUID)
	// Get a work by UUID
	// (GET /works/{uuid})
	GetWork(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID)
	// Add a movie work with the given uuid.
	// (PUT /works/{uuid}/movie)
	AddMovieWork(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID)
	// Create a new movie edition work with the given uuid.
	// (PUT /works/{uuid}/movie_edition)
	AddMovieEdition(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// AddFileToDisc operation middleware
func (siw *ServerInterfaceWrapper) AddFileToDisc(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "discUuid" -------------
	var discUuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "discUuid", r.PathValue("discUuid"), &discUuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "discUuid", Err: err})
		return
	}

	// ------------- Path parameter "fileUuid" -------------
	var fileUuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "fileUuid", r.PathValue("fileUuid"), &fileUuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "fileUuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddFileToDisc(w, r, discUuid, fileUuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSource operation middleware
func (siw *ServerInterfaceWrapper) GetSource(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", r.PathValue("uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSource(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddDiscSource operation middleware
func (siw *ServerInterfaceWrapper) AddDiscSource(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", r.PathValue("uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddDiscSource(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MarkDiscAllFilesAdded operation middleware
func (siw *ServerInterfaceWrapper) MarkDiscAllFilesAdded(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", r.PathValue("uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MarkDiscAllFilesAdded(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddFileSource operation middleware
func (siw *ServerInterfaceWrapper) AddFileSource(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", r.PathValue("uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddFileSource(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddEditionToMovie operation middleware
func (siw *ServerInterfaceWrapper) AddEditionToMovie(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "movieUuid" -------------
	var movieUuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "movieUuid", r.PathValue("movieUuid"), &movieUuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "movieUuid", Err: err})
		return
	}

	// ------------- Path parameter "editionUuid" -------------
	var editionUuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "editionUuid", r.PathValue("editionUuid"), &editionUuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "editionUuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddEditionToMovie(w, r, movieUuid, editionUuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWork operation middleware
func (siw *ServerInterfaceWrapper) GetWork(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", r.PathValue("uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWork(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddMovieWork operation middleware
func (siw *ServerInterfaceWrapper) AddMovieWork(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", r.PathValue("uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddMovieWork(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddMovieEdition operation middleware
func (siw *ServerInterfaceWrapper) AddMovieEdition(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", r.PathValue("uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddMovieEdition(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("PUT "+options.BaseURL+"/sources/{discUuid}/disc/file/{fileUuid}", wrapper.AddFileToDisc)
	m.HandleFunc("GET "+options.BaseURL+"/sources/{uuid}", wrapper.GetSource)
	m.HandleFunc("PUT "+options.BaseURL+"/sources/{uuid}/disc", wrapper.AddDiscSource)
	m.HandleFunc("PUT "+options.BaseURL+"/sources/{uuid}/disc/all_files_added", wrapper.MarkDiscAllFilesAdded)
	m.HandleFunc("PUT "+options.BaseURL+"/sources/{uuid}/file", wrapper.AddFileSource)
	m.HandleFunc("PUT "+options.BaseURL+"/works/{movieUuid}/movie/editions/{editionUuid}", wrapper.AddEditionToMovie)
	m.HandleFunc("GET "+options.BaseURL+"/works/{uuid}", wrapper.GetWork)
	m.HandleFunc("PUT "+options.BaseURL+"/works/{uuid}/movie", wrapper.AddMovieWork)
	m.HandleFunc("PUT "+options.BaseURL+"/works/{uuid}/movie_edition", wrapper.AddMovieEdition)

	return m
}

type AddFileToDiscRequestObject struct {
	DiscUuid openapi_types.UUID `json:"discUuid"`
	FileUuid openapi_types.UUID `json:"fileUuid"`
}

type AddFileToDiscResponseObject interface {
	VisitAddFileToDiscResponse(w http.ResponseWriter) error
}

type AddFileToDisc201JSONResponse Source

func (response AddFileToDisc201JSONResponse) VisitAddFileToDiscResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type AddFileToDisc400JSONResponse Error

func (response AddFileToDisc400JSONResponse) VisitAddFileToDiscResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type AddFileToDisc404JSONResponse Error

func (response AddFileToDisc404JSONResponse) VisitAddFileToDiscResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type AddFileToDisc500JSONResponse Error

func (response AddFileToDisc500JSONResponse) VisitAddFileToDiscResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetSourceRequestObject struct {
	Uuid openapi_types.UUID `json:"uuid"`
}

type GetSourceResponseObject interface {
	VisitGetSourceResponse(w http.ResponseWriter) error
}

type GetSource200JSONResponse Source

func (response GetSource200JSONResponse) VisitGetSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSource400JSONResponse Error

func (response GetSource400JSONResponse) VisitGetSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetSource404JSONResponse Error

func (response GetSource404JSONResponse) VisitGetSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetSource500JSONResponse Error

func (response GetSource500JSONResponse) VisitGetSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type AddDiscSourceRequestObject struct {
	Uuid openapi_types.UUID `json:"uuid"`
	Body *AddDiscSourceJSONRequestBody
}

type AddDiscSourceResponseObject interface {
	VisitAddDiscSourceResponse(w http.ResponseWriter) error
}

type AddDiscSource200Response struct {
}

func (response AddDiscSource200Response) VisitAddDiscSourceResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type AddDiscSource201Response struct {
}

func (response AddDiscSource201Response) VisitAddDiscSourceResponse(w http.ResponseWriter) error {
	w.WriteHeader(201)
	return nil
}

type AddDiscSource400JSONResponse Error

func (response AddDiscSource400JSONResponse) VisitAddDiscSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type AddDiscSource409JSONResponse Error

func (response AddDiscSource409JSONResponse) VisitAddDiscSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type AddDiscSource500JSONResponse Error

func (response AddDiscSource500JSONResponse) VisitAddDiscSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type MarkDiscAllFilesAddedRequestObject struct {
	Uuid openapi_types.UUID `json:"uuid"`
}

type MarkDiscAllFilesAddedResponseObject interface {
	VisitMarkDiscAllFilesAddedResponse(w http.ResponseWriter) error
}

type MarkDiscAllFilesAdded200JSONResponse Source

func (response MarkDiscAllFilesAdded200JSONResponse) VisitMarkDiscAllFilesAddedResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type MarkDiscAllFilesAdded404JSONResponse Error

func (response MarkDiscAllFilesAdded404JSONResponse) VisitMarkDiscAllFilesAddedResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type MarkDiscAllFilesAdded500JSONResponse Error

func (response MarkDiscAllFilesAdded500JSONResponse) VisitMarkDiscAllFilesAddedResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type AddFileSourceRequestObject struct {
	Uuid openapi_types.UUID `json:"uuid"`
	Body *AddFileSourceJSONRequestBody
}

type AddFileSourceResponseObject interface {
	VisitAddFileSourceResponse(w http.ResponseWriter) error
}

type AddFileSource200Response struct {
}

func (response AddFileSource200Response) VisitAddFileSourceResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type AddFileSource201Response struct {
}

func (response AddFileSource201Response) VisitAddFileSourceResponse(w http.ResponseWriter) error {
	w.WriteHeader(201)
	return nil
}

type AddFileSource400JSONResponse Error

func (response AddFileSource400JSONResponse) VisitAddFileSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type AddFileSource409JSONResponse Error

func (response AddFileSource409JSONResponse) VisitAddFileSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type AddFileSource500JSONResponse Error

func (response AddFileSource500JSONResponse) VisitAddFileSourceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type AddEditionToMovieRequestObject struct {
	MovieUuid   openapi_types.UUID `json:"movieUuid"`
	EditionUuid openapi_types.UUID `json:"editionUuid"`
}

type AddEditionToMovieResponseObject interface {
	VisitAddEditionToMovieResponse(w http.ResponseWriter) error
}

type AddEditionToMovie200Response struct {
}

func (response AddEditionToMovie200Response) VisitAddEditionToMovieResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type AddEditionToMovie400JSONResponse Error

func (response AddEditionToMovie400JSONResponse) VisitAddEditionToMovieResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type AddEditionToMovie404JSONResponse Error

func (response AddEditionToMovie404JSONResponse) VisitAddEditionToMovieResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type AddEditionToMovie500JSONResponse Error

func (response AddEditionToMovie500JSONResponse) VisitAddEditionToMovieResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkRequestObject struct {
	Uuid openapi_types.UUID `json:"uuid"`
}

type GetWorkResponseObject interface {
	VisitGetWorkResponse(w http.ResponseWriter) error
}

type GetWork200JSONResponse Work

func (response GetWork200JSONResponse) VisitGetWorkResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetWork400JSONResponse Error

func (response GetWork400JSONResponse) VisitGetWorkResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetWork404JSONResponse Error

func (response GetWork404JSONResponse) VisitGetWorkResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetWork500JSONResponse Error

func (response GetWork500JSONResponse) VisitGetWorkResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type AddMovieWorkRequestObject struct {
	Uuid openapi_types.UUID `json:"uuid"`
	Body *AddMovieWorkJSONRequestBody
}

type AddMovieWorkResponseObject interface {
	VisitAddMovieWorkResponse(w http.ResponseWriter) error
}

type AddMovieWork200Response struct {
}

func (response AddMovieWork200Response) VisitAddMovieWorkResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type AddMovieWork201Response struct {
}

func (response AddMovieWork201Response) VisitAddMovieWorkResponse(w http.ResponseWriter) error {
	w.WriteHeader(201)
	return nil
}

type AddMovieWork400JSONResponse Error

func (response AddMovieWork400JSONResponse) VisitAddMovieWorkResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type AddMovieWork409JSONResponse Error

func (response AddMovieWork409JSONResponse) VisitAddMovieWorkResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type AddMovieWork500JSONResponse Error

func (response AddMovieWork500JSONResponse) VisitAddMovieWorkResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type AddMovieEditionRequestObject struct {
	Uuid openapi_types.UUID `json:"uuid"`
	Body *AddMovieEditionJSONRequestBody
}

type AddMovieEditionResponseObject interface {
	VisitAddMovieEditionResponse(w http.ResponseWriter) error
}

type AddMovieEdition200Response struct {
}

func (response AddMovieEdition200Response) VisitAddMovieEditionResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type AddMovieEdition201Response struct {
}

func (response AddMovieEdition201Response) VisitAddMovieEditionResponse(w http.ResponseWriter) error {
	w.WriteHeader(201)
	return nil
}

type AddMovieEdition400JSONResponse Error

func (response AddMovieEdition400JSONResponse) VisitAddMovieEditionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type AddMovieEdition409JSONResponse Error

func (response AddMovieEdition409JSONResponse) VisitAddMovieEditionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type AddMovieEdition500JSONResponse Error

func (response AddMovieEdition500JSONResponse) VisitAddMovieEditionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Associates a file source with a disc source
	// (PUT /sources/{discUuid}/disc/file/{fileUuid})
	AddFileToDisc(ctx context.Context, request AddFileToDiscRequestObject) (AddFileToDiscResponseObject, error)
	// Get a source by UUID
	// (GET /sources/{uuid})
	GetSource(ctx context.Context, request GetSourceRequestObject) (GetSourceResponseObject, error)
	// Add a disc source with the given UUID.
	// (PUT /sources/{uuid}/disc)
	AddDiscSource(ctx context.Context, request AddDiscSourceRequestObject) (AddDiscSourceResponseObject, error)
	// Mark all files from the disc source as added
	// (PUT /sources/{uuid}/disc/all_files_added)
	MarkDiscAllFilesAdded(ctx context.Context, request MarkDiscAllFilesAddedRequestObject) (MarkDiscAllFilesAddedResponseObject, error)
	// Add a file source with the given UUID.
	// (PUT /sources/{uuid}/file)
	AddFileSource(ctx context.Context, request AddFileSourceRequestObject) (AddFileSourceResponseObject, error)
	// Associate an existing movie edition with a movie work.
	// (PUT /works/{movieUuid}/movie/editions/{editionUuid})
	AddEditionToMovie(ctx context.Context, request AddEditionToMovieRequestObject) (AddEditionToMovieResponseObject, error)
	// Get a work by UUID
	// (GET /works/{uuid})
	GetWork(ctx context.Context, request GetWorkRequestObject) (GetWorkResponseObject, error)
	// Add a movie work with the given uuid.
	// (PUT /works/{uuid}/movie)
	AddMovieWork(ctx context.Context, request AddMovieWorkRequestObject) (AddMovieWorkResponseObject, error)
	// Create a new movie edition work with the given uuid.
	// (PUT /works/{uuid}/movie_edition)
	AddMovieEdition(ctx context.Context, request AddMovieEditionRequestObject) (AddMovieEditionResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// AddFileToDisc operation middleware
func (sh *strictHandler) AddFileToDisc(w http.ResponseWriter, r *http.Request, discUuid openapi_types.UUID, fileUuid openapi_types.UUID) {
	var request AddFileToDiscRequestObject

	request.DiscUuid = discUuid
	request.FileUuid = fileUuid

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AddFileToDisc(ctx, request.(AddFileToDiscRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AddFileToDisc")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AddFileToDiscResponseObject); ok {
		if err := validResponse.VisitAddFileToDiscResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSource operation middleware
func (sh *strictHandler) GetSource(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	var request GetSourceRequestObject

	request.Uuid = uuid

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetSource(ctx, request.(GetSourceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSource")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetSourceResponseObject); ok {
		if err := validResponse.VisitGetSourceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AddDiscSource operation middleware
func (sh *strictHandler) AddDiscSource(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	var request AddDiscSourceRequestObject

	request.Uuid = uuid

	var body AddDiscSourceJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AddDiscSource(ctx, request.(AddDiscSourceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AddDiscSource")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AddDiscSourceResponseObject); ok {
		if err := validResponse.VisitAddDiscSourceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// MarkDiscAllFilesAdded operation middleware
func (sh *strictHandler) MarkDiscAllFilesAdded(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	var request MarkDiscAllFilesAddedRequestObject

	request.Uuid = uuid

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.MarkDiscAllFilesAdded(ctx, request.(MarkDiscAllFilesAddedRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "MarkDiscAllFilesAdded")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(MarkDiscAllFilesAddedResponseObject); ok {
		if err := validResponse.VisitMarkDiscAllFilesAddedResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AddFileSource operation middleware
func (sh *strictHandler) AddFileSource(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	var request AddFileSourceRequestObject

	request.Uuid = uuid

	var body AddFileSourceJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AddFileSource(ctx, request.(AddFileSourceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AddFileSource")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AddFileSourceResponseObject); ok {
		if err := validResponse.VisitAddFileSourceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AddEditionToMovie operation middleware
func (sh *strictHandler) AddEditionToMovie(w http.ResponseWriter, r *http.Request, movieUuid openapi_types.UUID, editionUuid openapi_types.UUID) {
	var request AddEditionToMovieRequestObject

	request.MovieUuid = movieUuid
	request.EditionUuid = editionUuid

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AddEditionToMovie(ctx, request.(AddEditionToMovieRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AddEditionToMovie")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AddEditionToMovieResponseObject); ok {
		if err := validResponse.VisitAddEditionToMovieResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetWork operation middleware
func (sh *strictHandler) GetWork(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	var request GetWorkRequestObject

	request.Uuid = uuid

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetWork(ctx, request.(GetWorkRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetWork")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetWorkResponseObject); ok {
		if err := validResponse.VisitGetWorkResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AddMovieWork operation middleware
func (sh *strictHandler) AddMovieWork(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	var request AddMovieWorkRequestObject

	request.Uuid = uuid

	var body AddMovieWorkJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AddMovieWork(ctx, request.(AddMovieWorkRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AddMovieWork")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AddMovieWorkResponseObject); ok {
		if err := validResponse.VisitAddMovieWorkResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AddMovieEdition operation middleware
func (sh *strictHandler) AddMovieEdition(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	var request AddMovieEditionRequestObject

	request.Uuid = uuid

	var body AddMovieEditionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AddMovieEdition(ctx, request.(AddMovieEditionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AddMovieEdition")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AddMovieEditionResponseObject); ok {
		if err := validResponse.VisitAddMovieEditionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xabY8aORL+K5bvpNuVOjQw5GX5lgubFR8mOe0wF52SKDLtArzptnttNxM04r+fbPcr",
	"bWiYTEaMMl9mENiuctVTT7103+JIJKngwLXC41usohUkxH6cMBWZ/xRUJFmqmeB4jCegCYsVInORaUQQ",
	"ZSpCSmQygh5CUx7FGQWK2ALpFeQ/IKbylT0c4FSKFKRmYKWQOH7LYlCvKQXaFjfllEVEg0I3K9ArkIjE",
	"MVqYHWghRWKlWB1WZA1oDsARsUcFGL6RJI0Bj7XMIMB6kwIe47kQMRCOtwEWki0nTL4jCbQlv5dsyTiJ",
	"EWUSIi3kBnGSABKLUmZdBr7cGINNisW4FKi0ZHxp5KVEr9qC7PU3SkOCzAJzUQnVvZhCsTAmaFwJh5yo",
	"MAHKSNgpeRtgCX9nTBoLf2xcO1cq2PHD5/IMMf8LIm20/11KIY36TQdGgnqsZxcj+1td63fvZ1/evr9+",
	"N/GZJwGlyHLvYcXP9fP+hBxhXGi0EBmnnbcvjvFd0VigG/IGfSXkDyHeLGwj/jgU5DAzRxzp9zARawa9",
	"5Ou60wZWBZ8BLs0R+y2gUojYgkVIC2SloRshvypP4JvvnRGcVi0rSIiBKPgfENmW96f7EW2AyMIS9py6",
	"KYb9Qb+8AuMaliDNHTTTPi/OzNd7D8NTHoFb6kGmTuh86mGn2QqQNRmaEE3mRuVfZpeT+a+IUeCaLRhI",
	"tBByzwVeDvvP2zfY8ZW7zl5n/U6ZU6YLtaXvwO0wpii8s8d/K1I6sNjVdmT+w8xq1zLQJm3avJT+C/SW",
	"vQB9wgV+/6XQm0x/wua72QqIliwi8Sf8a8NNzdWdQK8r5zPhlY3WNqnRPPf9U8ICj/E/wipLhnmKDG1+",
	"3AZ4kZPGobWWWLYBzjLmgdE1Z39n4MOMY5OGBYbDCxg9f/HyGbz6bf5sMKQXz8jo+Ytno+GLF4PR4OWo",
	"3x/gAC+ETIjGYyfSg2nj4euMUeVJffYDiRGRkmyM/ywcrq+nE4WIUiJiJh+hG6ZXSK+Y8uj5EQ+6Fe3j",
	"AI+6l10Y3zENidW182b5F1b5FiLsJh8UPgj5tQ2EpCDEQ951rGky2E5Edm4q1m4D7Ex4tEfyPHPAJ8Zn",
	"TY8cCZ2L7mXD7/HI6WGwe5VjsdWh2HHQMMsYX4i2wq//M7UqJoSTJeNLtGYUhMuJiHCaO0nhMinh/9oV",
	"b4gmsViiK5BrZuNmDVK5Qwe9fq9vq9MUOEkZHuOLXr93kZdq1uBhfnB4a4jKYGYbmk+h4aLw1vy1X1o8",
	"Z9qjOaVFgVLZm6L5BhV7TYova9CiqGmsLERjq6ok5miTJM3hhu9mYuJq5JRIkoAGqfD4Y8vp19NJvaau",
	"qISZn/PqlNsSHddEVo5z1b0LqyPQuA0OqWAtooXpIfwqFPb5LhU+m80qFVw5lhn2B66U5hq4dRdJ09g0",
	"Pkzw8C/l2KQ6/xCv5CnNwrZdYrrmCKksikCpRRbHNiBH/f69KeD6BI/8KV+TmFFk7AZKO7mjHy/XwBAJ",
	"id5WdXutX9gG+PnD3F6DNBSuQK5BIsgXBlhlSULkxkROweOq2WY4Vm8023ZnxQNZEe5L0L56WmeSm0Md",
	"OpDjtpJfl2wN3OaSVjD/AfqqiMijAznXWgskQUsG6z3xnN1/IPUfIJCuyuhBhfQHDyJr7tw8DxVIV+cc",
	"O3+A7XKcivONQ7MnSMKitj+UGPdnvY5weU2poZvTQ6Yu8VD+uZ+QsQT8b0E3J/muWRo/Tc+K6Zm/Zmy6",
	"aOtnKk+mykGQpdQW9LupOq8V9m88twz/24MRU9X72MgisQRCNwi+MaVdQc6UZa9iGH1WuZ/SHeLJr1Pn",
	"m95eRgtJHH+xc/EvpBilexnuktjuZM8U/QjOQ0SVI/Ym+ZmjDRJfN2bJ99kAPNKCwYanM3dC5FegpQ09",
	"cfqzJ3KDoi58lhD0hUMxkOvsfO+Y4A22T0/wdYmPI8Gf74OKO6bXegN4Unqtb3xKr0ekV/fk6/zSa6un",
	"9qZXO8ALby1M3XDNfgzzpwkqvM0/dQzZat08d2ZifLnzHKRJPrVzK/2qJ207q0sFez6aymfLM3GZP3g6",
	"mqoqgX6KKuX+uDlc00iGLwtj+lWqGe5H1Ac7JVRDudrw/acaq11WsBSytMaZD9YORGI+Y6vA32SDYyds",
	"H6xBTpmvfXCBdnR4WpM/7tmavfLTZK2UbUFzznM1i7nGVK0eFmH5mPRQzb03j3WX3JZr7honj6DUfnob",
	"5jvfhrljR1DLYSc1BG7fT9gKWKI6oRHI3/46v06gRkY7jUBmC+o9HPcFqrc7vFz3RoItMxCHG1+BsStn",
	"H9kVb4bcge9uVixaearoGxbHaA7l8O6sGfERv1b2XVxUXOQOdFQ2JE+0dBQtVe80nhM9HSKQA2xlzrCH",
	"+lhiAmuIRZoA17loHOBMxniMV1qn4zCMRUTilVB6/Kr/qo+3n7f/DwAA//8gNi3TGjAAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
